// Copyright (c) 2026 VATM ICPMS <sms@vatm.vn>.

import {
  Badge,
  Button,
  Card,
  IconChevronLeft,
  IconChevronRight,
  IconCrossLargeX,
  IconPlusLarge,
  IconRotateCw,
  IconTrashCan,
  Input,
  Option,
  PropertyRow,
  Select,
  Table,
  Tbody,
  Td,
  Textarea,
  Th,
  Thead,
  Tr,
  useToast,
} from "@probo/ui";
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { useMutation, useRelayEnvironment } from "react-relay";
import { useSearchParams } from "react-router";
import { usePageTitle } from "@probo/hooks";
import { fetchQuery, graphql } from "relay-runtime";
import { useOrganizationId } from "#/hooks/useOrganizationId";
import DocsQueryNode from "../../../__generated__/core/IcpmsDocumentsPageQuery.graphql";
import VersionsQueryNode from "../../../__generated__/core/IcpmsDocumentVersionsTabQuery.graphql";
import LatestParseJobQueryNode from "../../../__generated__/core/IcpmsIngestionJobsPageLatestParseJobQuery.graphql";
import RunParserMutationNode from "../../../__generated__/core/IcpmsIngestionJobsPageCreateVietnameseParseJobMutation.graphql";

function extractError(err: Error): string {
  const m = err.message.match(/got error\(s\):\s*(.+?)(?:\s*See the error|$)/s);
  return m ? m[1].trim() : err.message;
}

// Tooltip render qua portal với position: fixed — không bị vùng cuộn của
// bảng cắt mất như tooltip absolute đặt trong hàng.
function HoverTooltip({ trigger, children, width = 320 }: {
  trigger: ReactNode;
  children: ReactNode;
  width?: number;
}) {
  const anchorRef = useRef<HTMLSpanElement>(null);
  const [pos, setPos] = useState<{ top: number; left: number; above: boolean } | null>(null);

  const show = () => {
    const rect = anchorRef.current?.getBoundingClientRect();
    if (!rect) return;
    const margin = 8;
    const spaceAbove = rect.top;
    const above = spaceAbove > 240; // đủ chỗ thì hiện phía trên, không thì phía dưới
    const left = Math.max(margin, Math.min(rect.left, window.innerWidth - width - margin));
    setPos({
      top: above ? rect.top - margin : rect.bottom + margin,
      left,
      above,
    });
  };

  return (
    <span
      ref={anchorRef}
      onMouseEnter={show}
      onMouseLeave={() => setPos(null)}
      className="inline-block"
    >
      {trigger}
      {pos && createPortal(
        <div
          className="fixed text-white text-xs rounded-lg shadow-2xl p-3 pointer-events-none"
          style={{
            top: pos.top,
            left: pos.left,
            width,
            zIndex: 9999,
            backgroundColor: "#111827",
            transform: pos.above ? "translateY(-100%)" : undefined,
          }}
        >
          {children}
        </div>,
        document.body,
      )}
    </span>
  );
}

const ListQueryNode = graphql`
  query IcpmsRequirementsPageListQuery($organizationId: ID!) {
    icpmsRequirementsForOrganization(organizationId: $organizationId) {
      id
      organizationId
      documentId
      document {
        id
        code
        title
      }
      documentVersionId
      parseJobId
      sourceSectionId
      sourceReference
      sourceSectionSummary
      requirementCode
      title
      description
      requirementType
      applicabilityStatus
      applicabilityNote
      reviewStatus
      priority
      candidateScore
      isAutoGenerated
      aiReviewedAt
      createdAt
      updatedAt
    }
  }
`;

const ApproveMutationNode = graphql`
  mutation IcpmsRequirementsPageApproveMutation($parseJobId: ID!) {
    approveIcpmsRequirementsForParseJob(parseJobId: $parseJobId)
  }
`;

const GenerateMutationNode = graphql`
  mutation IcpmsRequirementsPageGenerateMutation($input: GenerateRequirementsFromParseJobInput!) {
    generateRequirementsFromParseJob(input: $input) {
      requirementsCreated
    }
  }
`;

const UpdateMutationNode = graphql`
  mutation IcpmsRequirementsPageUpdateMutation($input: UpdateIcpmsRequirementInput!) {
    updateIcpmsRequirement(input: $input) {
      requirement {
        id
        title
        description
        requirementType
        applicabilityStatus
        reviewStatus
        priority
        updatedAt
      }
    }
  }
`;

const DeleteDocMutationNode = graphql`
  mutation IcpmsRequirementsPageDeleteDocMutation($documentId: ID!) {
    deleteIcpmsRequirementsForDocument(documentId: $documentId)
  }
`;

const DeleteVersionMutationNode = graphql`
  mutation IcpmsRequirementsPageDeleteVersionMutation($documentVersionId: ID!) {
    deleteIcpmsRequirementsForVersion(documentVersionId: $documentVersionId)
  }
`;

const DeleteOneMutationNode = graphql`
  mutation IcpmsRequirementsPageDeleteOneMutation($id: ID!) {
    deleteIcpmsRequirement(id: $id)
  }
`;

import type {
  IcpmsRequirementsPageListQuery$data,
  IcpmsRequirementType,
  IcpmsRequirementReviewStatus,
  IcpmsApplicabilityStatus,
  IcpmsRequirementPriority,
} from "../../../__generated__/core/IcpmsRequirementsPageListQuery.graphql";
import type { IcpmsDocumentsPageQuery$data } from "../../../__generated__/core/IcpmsDocumentsPageQuery.graphql";
import type { IcpmsDocumentVersionsTabQuery$data } from "../../../__generated__/core/IcpmsDocumentVersionsTabQuery.graphql";
import type { IcpmsIngestionJobsPageLatestParseJobQuery$data } from "../../../__generated__/core/IcpmsIngestionJobsPageLatestParseJobQuery.graphql";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Requirement = IcpmsRequirementsPageListQuery$data["icpmsRequirementsForOrganization"][number];

interface DocOpt { id: string; code: string; title: string; }
interface VersionOpt {
  id: string;
  versionCode: string;
  versionName: string;
  latestIngestionJob: { id: string; status: string } | null | undefined;
}
type ParseJobOpt = IcpmsIngestionJobsPageLatestParseJobQuery$data["latestParseJobForIngestionJob"];

interface FilterState {
  search: string;
  requirementType: IcpmsRequirementType | "";
  reviewStatus: IcpmsRequirementReviewStatus | "";
  applicabilityStatus: IcpmsApplicabilityStatus | "";
  priority: IcpmsRequirementPriority | "";
}

// ---------------------------------------------------------------------------
// Labels & Variants
// ---------------------------------------------------------------------------

const REQ_TYPE_LABELS: Record<IcpmsRequirementType, string> = {
  OBLIGATION: "Nghĩa vụ",
  PROHIBITION: "Cấm đoán",
  RESPONSIBILITY: "Trách nhiệm",
  PROCESS: "Quy trình",
  RECORD: "Hồ sơ",
  REPORTING: "Báo cáo",
  TRAINING: "Đào tạo",
  MONITORING: "Giám sát",
  REVIEW: "Rà soát",
  EVIDENCE: "Bằng chứng",
  INFORMATION: "Thông tin",
  OTHER: "Khác",
};

const REVIEW_STATUS_LABELS: Record<IcpmsRequirementReviewStatus, string> = {
  CANDIDATE: "Ứng viên",
  NEEDS_REVIEW: "Cần rà soát",
  REVIEWED: "Đã rà soát",
  APPROVED: "Đã duyệt",
  REJECTED: "Từ chối",
  ARCHIVED: "Lưu trữ",
};

const APPLICABILITY_LABELS: Record<IcpmsApplicabilityStatus, string> = {
  APPLICABLE: "Áp dụng",
  NOT_APPLICABLE: "Không áp dụng",
  NEEDS_REVIEW: "Cần xem xét",
  PARTIALLY_APPLICABLE: "Áp dụng một phần",
  UNKNOWN: "Chưa xác định",
};

const PRIORITY_LABELS: Record<IcpmsRequirementPriority, string> = {
  HIGH: "Cao",
  MEDIUM: "Trung bình",
  LOW: "Thấp",
};

const REVIEW_STATUS_VARIANTS: Record<IcpmsRequirementReviewStatus, "warning" | "info" | "success" | "danger" | "neutral"> = {
  CANDIDATE: "neutral",
  NEEDS_REVIEW: "warning",
  REVIEWED: "info",
  APPROVED: "success",
  REJECTED: "danger",
  ARCHIVED: "neutral",
};

const PRIORITY_VARIANTS: Record<IcpmsRequirementPriority, "danger" | "warning" | "neutral"> = {
  HIGH: "danger",
  MEDIUM: "warning",
  LOW: "neutral",
};

const APPLICABILITY_VARIANTS: Record<IcpmsApplicabilityStatus, "success" | "neutral" | "warning" | "info"> = {
  APPLICABLE: "success",
  NOT_APPLICABLE: "neutral",
  NEEDS_REVIEW: "warning",
  PARTIALLY_APPLICABLE: "info",
  UNKNOWN: "neutral",
};

// ---------------------------------------------------------------------------
// Generate Dialog
// ---------------------------------------------------------------------------

function GenerateDialog({
  onClose,
  onGenerated,
  preselectedDocId,
  preselectedVerId,
}: {
  onClose: () => void;
  onGenerated: () => void;
  preselectedDocId?: string;
  preselectedVerId?: string;
}) {
  const env = useRelayEnvironment();
  const organizationId = useOrganizationId();
  const { toast } = useToast();

  const [docs, setDocs] = useState<DocOpt[]>([]);
  const [docsLoading, setDocsLoading] = useState(true);
  const [selectedDoc, setSelectedDoc] = useState<DocOpt | null>(null);

  const [versions, setVersions] = useState<VersionOpt[]>([]);
  const [versionsLoading, setVersionsLoading] = useState(false);
  const [selectedVersion, setSelectedVersion] = useState<VersionOpt | null>(null);

  const [parseJob, setParseJob] = useState<ParseJobOpt | null | undefined>(undefined);
  const [parseJobLoading, setParseJobLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [progressPct, setProgressPct] = useState(0);
  const [error, setError] = useState("");

  const [commitGenerate] = useMutation(GenerateMutationNode);
  const [commitRunParser, isRunningParser] = useMutation(RunParserMutationNode);

  useEffect(() => {
    if (!isGenerating) { setProgressPct(0); return; }
    const interval = setInterval(() => {
      setProgressPct((prev) => prev >= 90 ? prev : prev + (90 - prev) * 0.06);
    }, 400);
    return () => clearInterval(interval);
  }, [isGenerating]);

  useEffect(() => {
    if (!organizationId) return;
    setDocsLoading(true);
    fetchQuery(env, DocsQueryNode, { organizationId }).subscribe({
      next: (data: unknown) => {
        const d = data as IcpmsDocumentsPageQuery$data;
        const edges = (d.organization as any).icpmsDocuments?.edges ?? [];
        const list: DocOpt[] = edges.map((e: any) => e.node as DocOpt);
        setDocs(list);
        if (preselectedDocId) {
          const pre = list.find((d) => d.id === preselectedDocId) ?? null;
          setSelectedDoc(pre);
        }
        setDocsLoading(false);
      },
      error: () => setDocsLoading(false),
    });
  }, [env, organizationId, preselectedDocId]);

  useEffect(() => {
    if (!selectedDoc) { setVersions([]); setSelectedVersion(null); return; }
    setVersionsLoading(true);
    fetchQuery(env, VersionsQueryNode, { documentId: selectedDoc.id }).subscribe({
      next: (data: unknown) => {
        const d = data as IcpmsDocumentVersionsTabQuery$data;
        if (d.document.__typename === "IcpmsDocument") {
          const edges = (d.document as any).versions?.edges ?? [];
          const list: VersionOpt[] = edges.map((e: any) => e.node as VersionOpt);
          setVersions(list);
          if (preselectedVerId) {
            const pre = list.find((v) => v.id === preselectedVerId) ?? null;
            setSelectedVersion(pre);
          }
        }
        setVersionsLoading(false);
      },
      error: () => setVersionsLoading(false),
    });
  }, [env, selectedDoc, preselectedVerId]);

  useEffect(() => {
    if (!selectedVersion) { setParseJob(undefined); return; }
    const ingJob = selectedVersion.latestIngestionJob;
    if (!ingJob || ingJob.status !== "COMPLETED") { setParseJob(null); return; }
    setParseJobLoading(true);
    fetchQuery(env, LatestParseJobQueryNode, { ingestionJobId: ingJob.id }).subscribe({
      next: (data: unknown) => {
        const d = data as IcpmsIngestionJobsPageLatestParseJobQuery$data;
        setParseJob(d.latestParseJobForIngestionJob ?? null);
        setParseJobLoading(false);
      },
      error: () => { setParseJob(null); setParseJobLoading(false); },
    });
  }, [env, selectedVersion]);

  const handleRunParser = useCallback(() => {
    const ingJobId = selectedVersion?.latestIngestionJob?.id;
    if (!ingJobId) return;
    commitRunParser({
      variables: { input: { ingestionJobId: ingJobId } },
      onCompleted: (data: unknown) => {
        const job = (data as any).createAndRunVietnameseParseJob?.parseJob ?? null;
        setParseJob(job as ParseJobOpt);
        if (!job) toast({ title: "Lỗi", description: "Parser chạy xong nhưng không trả về dữ liệu", variant: "error" });
      },
      onError: (err) => toast({ title: "Lỗi khi chạy parser", description: extractError(err), variant: "error" }),
    });
  }, [selectedVersion, commitRunParser, toast]);

  const handleGenerate = useCallback(() => {
    if (!parseJob || parseJob.status !== "COMPLETED") return;
    setIsGenerating(true);
    setError("");
    commitGenerate({
      variables: { input: { parseJobId: parseJob.id } },
      onCompleted: (data: unknown) => {
        const created = (data as any).generateRequirementsFromParseJob?.requirementsCreated ?? 0;
        setProgressPct(100);
        setTimeout(() => {
          toast({ title: "Thành công", description: `Đã tạo ${created} yêu cầu mới`, variant: "success" });
          onClose();
          setIsGenerating(false);
          setTimeout(onGenerated, 150);
        }, 400);
      },
      onError: (err) => { setError(extractError(err)); setIsGenerating(false); },
    });
  }, [parseJob, commitGenerate, toast, onGenerated, onClose]);

  const canGenerate = parseJob?.status === "COMPLETED" && !isGenerating;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <Card className="w-full max-w-lg">
        <div className="flex items-center justify-between px-6 py-4 border-b border-border-mid">
          <h2 className="text-base font-semibold text-txt-primary">Tạo yêu cầu từ bản phân tích</h2>
          <Button variant="tertiary" onClick={onClose}>
            <IconCrossLargeX className="h-4 w-4" />
          </Button>
        </div>

        <div className="px-6 py-5 space-y-4">
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-txt-secondary">Tài liệu</label>
            <Select
              value={selectedDoc?.id || undefined}
              onValueChange={(v) => {
                const doc = docs.find((d) => d.id === v) ?? null;
                setSelectedDoc(doc);
                setSelectedVersion(null);
                setParseJob(undefined);
              }}
              placeholder={docsLoading ? "Đang tải..." : "Chọn tài liệu..."}
            >
              {docs.map((d) => (
                <Option key={d.id} value={d.id}>{d.code} — {d.title}</Option>
              ))}
            </Select>
          </div>

          {selectedDoc && (
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-txt-secondary">Phiên bản</label>
              <Select
                value={selectedVersion?.id || undefined}
                onValueChange={(v) => {
                  const ver = versions.find((v2) => v2.id === v) ?? null;
                  setSelectedVersion(ver);
                  setParseJob(undefined);
                }}
                placeholder={versionsLoading ? "Đang tải..." : "Chọn phiên bản..."}
              >
                {versions.map((v) => (
                  <Option key={v.id} value={v.id}>{v.versionCode} — {v.versionName}</Option>
                ))}
              </Select>
            </div>
          )}

          {selectedVersion && (
            <div className="rounded-lg border border-border-mid p-3.5 text-sm bg-level-1">
              {parseJobLoading ? (
                <p className="text-txt-tertiary italic">Đang kiểm tra bản phân tích...</p>
              ) : selectedVersion.latestIngestionJob == null ? (
                <p className="text-txt-secondary">
                  Phiên bản này chưa có quá trình trích xuất. Vui lòng tạo trong mục <strong>Bóc tách tài liệu</strong> trước.
                </p>
              ) : selectedVersion.latestIngestionJob.status !== "COMPLETED" ? (
                <p className="text-txt-secondary">
                  Quá trình trích xuất chưa hoàn thành ({selectedVersion.latestIngestionJob.status}).
                </p>
              ) : parseJob == null ? (
                <div className="space-y-3">
                  <p className="text-txt-secondary">Tài liệu này chưa có bản phân tích cấu trúc.</p>
                  <Button variant="secondary" onClick={handleRunParser} disabled={isRunningParser}>
                    {isRunningParser ? "Đang chạy parser..." : "Chạy parser văn bản ngay"}
                  </Button>
                </div>
              ) : parseJob.status === "COMPLETED" ? (
                <div className="flex items-center gap-3">
                  <Badge variant="success">Sẵn sàng</Badge>
                  <span className="text-txt-secondary text-xs">
                    {parseJob.totalSections} mục
                  </span>
                </div>
              ) : (
                <p className="text-txt-secondary">Bản phân tích chưa hoàn thành ({parseJob.status}).</p>
              )}
            </div>
          )}

          {isGenerating && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs text-txt-secondary">
                <span>{progressPct < 100 ? `Đang tạo yêu cầu từ ${parseJob?.totalSections ?? 0} mục...` : "Hoàn thành!"}</span>
                <span className="font-mono font-medium">{Math.round(progressPct)}%</span>
              </div>
              <div className="w-full h-1.5 bg-border-mid rounded-full overflow-hidden">
                <div className="h-full bg-primary rounded-full transition-all duration-300" style={{ width: `${progressPct}%` }} />
              </div>
            </div>
          )}

          {error && <p className="text-xs text-danger-500 bg-danger-50 rounded px-3 py-2">{error}</p>}
        </div>

        <div className="flex gap-2 justify-end px-6 py-4 border-t border-border-mid">
          <Button variant="tertiary" onClick={onClose} disabled={isGenerating}>Hủy</Button>
          <Button onClick={handleGenerate} disabled={!canGenerate}>
            {isGenerating ? `Đang xử lý... ${Math.round(progressPct)}%` : "Tạo yêu cầu"}
          </Button>
        </div>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Requirement Detail Panel
// ---------------------------------------------------------------------------

// Title (max 200 ký tự) và description thực chất là một đoạn văn bản bị parser
// cắt đôi. Gộp lại thành một nội dung liền mạch để hiển thị/chỉnh sửa.
function mergeReqContent(title: string, description?: string | null): string {
  const t = (title ?? "").trim();
  const d = (description ?? "").trim();
  if (!d) return t;
  // Tiêu đề kết thúc giữa chừng (không có dấu câu cuối) → phần mô tả là phần
  // tiếp nối của câu, nối liền bằng dấu cách; ngược lại xuống đoạn mới.
  return /[.!?:;)]$/.test(t) ? `${t}\n\n${d}` : `${t} ${d}`;
}

// Tách ngược lại khi lưu: title = ~200 ký tự đầu (cắt tại ranh giới từ),
// description = phần còn lại. Không đổi schema phía server.
function splitReqContent(content: string): { title: string; description: string | null } {
  const text = content.trim();
  const chars = Array.from(text);
  const LIMIT = 200;
  if (chars.length <= LIMIT) return { title: text, description: null };
  let cut = LIMIT;
  for (let i = LIMIT; i > LIMIT - 60; i--) {
    if (/\s/.test(chars[i])) { cut = i; break; }
  }
  return {
    title: chars.slice(0, cut).join("").trim(),
    description: chars.slice(cut).join("").trim() || null,
  };
}

function RequirementDetailPanel({
  req,
  onClose,
  onSaved,
}: {
  req: Requirement;
  onClose: () => void;
  onSaved: (updated: Partial<Requirement>) => void;
}) {
  const [content, setContent] = useState(() => mergeReqContent(req.title, req.description));
  const [reqType, setReqType] = useState<IcpmsRequirementType>(req.requirementType);
  const [appStatus, setAppStatus] = useState<IcpmsApplicabilityStatus>(req.applicabilityStatus);
  const [reviewStatus, setReviewStatus] = useState<IcpmsRequirementReviewStatus>(req.reviewStatus);
  const [priority, setPriority] = useState<IcpmsRequirementPriority>(req.priority);
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState("");
  const { toast } = useToast();
  const [commitUpdate] = useMutation(UpdateMutationNode);

  const handleSave = useCallback(() => {
    setIsSaving(true);
    setSaveError("");
    const { title, description } = splitReqContent(content);
    commitUpdate({
      variables: {
        input: { id: req.id, title, description, requirementType: reqType, applicabilityStatus: appStatus, reviewStatus, priority },
      },
      onCompleted: () => {
        setIsSaving(false);
        toast({ title: "Thành công", description: "Đã lưu yêu cầu", variant: "success" });
        onSaved({ title, description: description ?? undefined, requirementType: reqType, applicabilityStatus: appStatus, reviewStatus, priority });
      },
      onError: (err) => { setIsSaving(false); setSaveError(extractError(err)); },
    });
  }, [req.id, content, reqType, appStatus, reviewStatus, priority, commitUpdate, toast, onSaved]);

  const createdAt = req.createdAt
    ? new Date(req.createdAt as string).toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" })
    : "—";

  return (
    <>
      <div className="fixed inset-0 z-30 bg-black/20" onClick={onClose} aria-hidden="true" />
      <div className="fixed right-0 top-0 bottom-[40px] w-[520px] z-40 flex flex-col bg-level-0 shadow-2xl border-l border-border-mid">
        <div className="flex items-start justify-between px-5 py-4 border-b border-border-mid">
          <div className="flex-1 min-w-0 pr-3">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-mono text-txt-tertiary bg-level-2 px-2 py-0.5 rounded">{req.requirementCode}</span>
              <Badge variant={REVIEW_STATUS_VARIANTS[req.reviewStatus]}>{REVIEW_STATUS_LABELS[req.reviewStatus]}</Badge>
              <Badge variant={PRIORITY_VARIANTS[req.priority]}>{PRIORITY_LABELS[req.priority]}</Badge>
            </div>
            <h2 className="text-sm font-semibold text-txt-primary line-clamp-2 leading-snug">{req.title}</h2>
          </div>
          <Button variant="tertiary" onClick={onClose} className="shrink-0 mt-0.5">
            <IconCrossLargeX className="h-4 w-4" />
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
          <div className="space-y-3">
            <div>
              <p className="text-xs font-medium text-txt-tertiary mb-1.5">Nội dung yêu cầu</p>
              <Textarea
                variant="bordered"
                value={content}
                onChange={(e) => setContent(e.target.value)}
                rows={6}
                autogrow
                placeholder="Nội dung yêu cầu"
              />
            </div>
          </div>

          <div className="border-t border-border-mid pt-4 space-y-3">
            <p className="text-xs font-semibold text-txt-tertiary uppercase tracking-wide">Phân loại</p>
            <PropertyRow label="Loại yêu cầu">
              <Select value={reqType} onValueChange={(v) => setReqType(v as IcpmsRequirementType)}>
                {(Object.keys(REQ_TYPE_LABELS) as IcpmsRequirementType[]).map((t) => (
                  <Option key={t} value={t}>{REQ_TYPE_LABELS[t]}</Option>
                ))}
              </Select>
            </PropertyRow>
            <PropertyRow label="Trạng thái rà soát">
              <Select value={reviewStatus} onValueChange={(v) => setReviewStatus(v as IcpmsRequirementReviewStatus)}>
                {(Object.keys(REVIEW_STATUS_LABELS) as IcpmsRequirementReviewStatus[]).map((s) => (
                  <Option key={s} value={s}>{REVIEW_STATUS_LABELS[s]}</Option>
                ))}
              </Select>
            </PropertyRow>
            <PropertyRow label="Mức độ áp dụng">
              <Select value={appStatus} onValueChange={(v) => setAppStatus(v as IcpmsApplicabilityStatus)}>
                {(Object.keys(APPLICABILITY_LABELS) as IcpmsApplicabilityStatus[]).map((s) => (
                  <Option key={s} value={s}>{APPLICABILITY_LABELS[s]}</Option>
                ))}
              </Select>
            </PropertyRow>
            <PropertyRow label="Ưu tiên">
              <Select value={priority} onValueChange={(v) => setPriority(v as IcpmsRequirementPriority)}>
                {(Object.keys(PRIORITY_LABELS) as IcpmsRequirementPriority[]).map((p) => (
                  <Option key={p} value={p}>{PRIORITY_LABELS[p]}</Option>
                ))}
              </Select>
            </PropertyRow>
          </div>

          <div className="border-t border-border-mid pt-4 space-y-2">
            <p className="text-xs font-semibold text-txt-tertiary uppercase tracking-wide">Thông tin</p>
            <div className="flex items-center justify-between py-1">
              <span className="text-xs text-txt-tertiary">Điểm ứng viên</span>
              <span className="text-xs font-mono font-semibold text-txt-secondary">{req.candidateScore}</span>
            </div>
            <div className="flex items-center justify-between py-1">
              <span className="text-xs text-txt-tertiary">Tự động tạo</span>
              <Badge variant={req.isAutoGenerated ? "info" : "neutral"}>{req.isAutoGenerated ? "Có" : "Thủ công"}</Badge>
            </div>
            <div className="flex items-center justify-between py-1">
              <span className="text-xs text-txt-tertiary">Ngày tạo</span>
              <span className="text-xs text-txt-secondary">{createdAt}</span>
            </div>
          </div>
        </div>

        {saveError && (
          <div className="px-5 py-2 bg-danger-50 border-t border-danger-100">
            <p className="text-xs text-danger-600">{saveError}</p>
          </div>
        )}

        <div className="px-5 py-3.5 border-t border-border-mid flex justify-end gap-2">
          <Button variant="tertiary" onClick={onClose}>Đóng</Button>
          <Button onClick={handleSave} disabled={isSaving || !content.trim()}>{isSaving ? "Đang lưu..." : "Lưu thay đổi"}</Button>
        </div>
      </div>
    </>
  );
}

// ---------------------------------------------------------------------------
// Step 1: Document Picker
// ---------------------------------------------------------------------------

interface DocSummary {
  id: string;
  code: string;
  title: string;
  versionCount: number;
  reqCount: number;
  approvedCount: number;
  needsReviewCount: number;
  highPriorityCount: number;
}

function ConfirmDeleteDialog({
  label,
  type,
  onConfirm,
  onCancel,
  loading,
}: {
  label: string;
  type: "doc" | "version";
  onConfirm: () => void;
  onCancel: () => void;
  loading: boolean;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
      <Card className="w-full max-w-sm p-6">
        <h2 className="text-base font-semibold text-txt-primary mb-2">
          {type === "doc" ? "Xóa yêu cầu của tài liệu" : "Xóa yêu cầu của phiên bản"}
        </h2>
        <p className="text-sm text-txt-secondary mb-5">
          Tất cả yêu cầu của <span className="font-medium text-txt-primary">"{label}"</span> sẽ bị xóa vĩnh viễn.
          Hành động này không thể hoàn tác.
        </p>
        <div className="flex justify-end gap-2">
          <Button variant="tertiary" onClick={onCancel} disabled={loading}>Hủy</Button>
          <Button variant="danger" onClick={onConfirm} disabled={loading}>
            {loading ? "Đang xóa..." : "Xóa"}
          </Button>
        </div>
      </Card>
    </div>
  );
}

function DocumentPickerView({
  docs,
  loading,
  onSelect,
  onRefresh,
  onGenerate,
  onDeleteDoc,
}: {
  docs: DocSummary[];
  loading: boolean;
  onSelect: (docId: string) => void;
  onRefresh: () => void;
  onGenerate: () => void;
  onDeleteDoc: (docId: string, label: string) => void;
}) {
  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-border-mid shrink-0">
        <div className="flex gap-3 items-start">
          <span
            aria-hidden
            className="mt-1.5 h-7 w-[3px] rounded-full shrink-0"
            style={{ background: "linear-gradient(180deg, #0a3d8f 0%, #2563eb 100%)" }}
          />
          <div>
            <h1 className="text-3xl font-bold tracking-tight" style={{ color: "#0a3d8f" }}>Yêu cầu ICPMS</h1>
            <p className="text-sm text-txt-secondary mt-1">Chọn tài liệu để xem danh sách yêu cầu theo phiên bản</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="tertiary" onClick={onRefresh} disabled={loading}>
            <IconRotateCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
          </Button>
          <Button onClick={onGenerate}>
            <IconPlusLarge className="h-4 w-4 mr-1.5" />
            Tạo từ bản phân tích
          </Button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {loading && docs.length === 0 ? (
          <div className="flex items-center justify-center py-20 text-txt-tertiary text-sm">Đang tải...</div>
        ) : docs.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 gap-3 text-txt-tertiary">
            <p className="text-sm">Chưa có yêu cầu nào.</p>
            <Button onClick={onGenerate}>
              <IconPlusLarge className="h-4 w-4 mr-1.5" />
              Tạo từ bản phân tích
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {docs.map((doc, idx) => (
              <div key={doc.id} className="relative rounded-xl border border-border-mid bg-level-0 hover:border-primary hover:shadow-md transition-all duration-150 group">
                <button
                  onClick={() => onSelect(doc.id)}
                  className="w-full text-left p-5"
                >
                  <div className="flex items-start justify-between gap-2 mb-3">
                    <div className="min-w-0">
                      <span className="text-xs font-mono text-txt-tertiary">
                        <span className="inline-flex items-center justify-center h-5 min-w-5 px-1 mr-1.5 rounded-full bg-level-2 text-txt-secondary font-semibold not-italic tabular-nums align-middle">{idx + 1}</span>
                        {doc.code}
                      </span>
                      <h3 className="text-sm font-semibold text-txt-primary line-clamp-2 mt-0.5 group-hover:text-primary transition-colors">
                        {doc.title}
                      </h3>
                    </div>
                    <IconChevronRight className="h-4 w-4 text-txt-tertiary shrink-0 mt-1 group-hover:text-primary transition-colors" />
                  </div>

                  <div className="flex items-center gap-3 text-xs text-txt-secondary pt-3 border-t border-border-mid">
                    <span className="flex items-center gap-1">
                      <span className="font-semibold text-txt-primary">{doc.versionCount}</span>
                      phiên bản
                    </span>
                    <span className="text-border-mid">·</span>
                    <span className="flex items-center gap-1">
                      <span className="font-semibold text-txt-primary">{doc.reqCount}</span>
                      yêu cầu
                    </span>
                  </div>

                  {(doc.needsReviewCount > 0 || doc.approvedCount > 0 || doc.highPriorityCount > 0) && (
                    <div className="flex items-center gap-2 mt-2.5 flex-wrap">
                      {doc.needsReviewCount > 0 && (
                        <Badge variant="warning">{doc.needsReviewCount} cần rà soát</Badge>
                      )}
                      {doc.approvedCount > 0 && (
                        <Badge variant="success">{doc.approvedCount} đã duyệt</Badge>
                      )}
                      {doc.highPriorityCount > 0 && (
                        <Badge variant="danger">{doc.highPriorityCount} ưu tiên cao</Badge>
                      )}
                    </div>
                  )}
                </button>
                {/* Delete button — visible on hover */}
                <button
                  onClick={(e) => { e.stopPropagation(); onDeleteDoc(doc.id, doc.title); }}
                  className="absolute top-3 right-8 p-1 rounded text-txt-tertiary opacity-0 group-hover:opacity-100 hover:text-red-500 hover:bg-red-50 transition-all"
                  title="Xóa yêu cầu của tài liệu này"
                >
                  <IconTrashCan className="h-3.5 w-3.5" />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 2: Version Picker
// ---------------------------------------------------------------------------

interface VersionSummary {
  id: string;
  versionCode: string;
  versionName: string;
  reqCount: number;
  approvedCount: number;
  needsReviewCount: number;
  highPriorityCount: number;
}

function VersionPickerView({
  doc,
  versions,
  loading,
  onSelect,
  onBack,
  onGenerate,
  onDeleteDoc,
  onDeleteVersion,
}: {
  doc: DocSummary | undefined;
  versions: VersionSummary[];
  loading: boolean;
  onSelect: (verId: string) => void;
  onBack: () => void;
  onGenerate: () => void;
  onDeleteDoc: () => void;
  onDeleteVersion: (verId: string, label: string) => void;
}) {
  return (
    <div className="flex flex-col h-full">
      {/* Header + Breadcrumb */}
      <div className="px-6 py-4 border-b border-border-mid shrink-0">
        <button
          onClick={onBack}
          className="flex items-center gap-1 text-xs text-txt-tertiary hover:text-txt-primary transition-colors mb-2"
        >
          <IconChevronLeft className="h-3.5 w-3.5" />
          Yêu cầu ICPMS
        </button>
        <div className="flex items-center justify-between">
          <div>
            <span className="text-xs font-mono text-txt-tertiary">{doc?.code}</span>
            <h1 className="text-lg font-semibold text-txt-primary">{doc?.title ?? "Tài liệu"}</h1>
            <p className="text-xs text-txt-tertiary mt-0.5">Chọn phiên bản để xem danh sách yêu cầu</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="tertiary" onClick={onDeleteDoc} title="Xóa tất cả yêu cầu của tài liệu này">
              <IconTrashCan className="h-4 w-4 mr-1.5" />
              Xóa tài liệu
            </Button>
            <Button onClick={onGenerate}>
              <IconPlusLarge className="h-4 w-4 mr-1.5" />
              Tạo từ bản phân tích
            </Button>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {loading ? (
          <div className="flex items-center justify-center py-20 text-txt-tertiary text-sm">Đang tải phiên bản...</div>
        ) : versions.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 gap-2 text-txt-tertiary">
            <p className="text-sm">Tài liệu này chưa có yêu cầu nào.</p>
            <Button onClick={onGenerate}>
              <IconPlusLarge className="h-4 w-4 mr-1.5" />
              Tạo từ bản phân tích
            </Button>
          </div>
        ) : (
          <div className="max-w-2xl space-y-3">
            {versions.map((ver, idx) => (
              <div key={ver.id} className="relative rounded-xl border border-border-mid bg-level-0 hover:border-primary hover:shadow-sm transition-all duration-150 group flex items-center">
                <button
                  onClick={() => onSelect(ver.id)}
                  className="flex-1 text-left p-4 flex items-center justify-between min-w-0"
                >
                  <span className="inline-flex items-center justify-center h-6 min-w-6 px-1.5 mr-3 rounded-full bg-level-2 text-xs font-semibold text-txt-secondary tabular-nums shrink-0">
                    {idx + 1}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-semibold text-txt-primary group-hover:text-primary transition-colors">
                        {ver.versionCode}
                      </span>
                      {ver.versionName && (
                        <span className="text-xs text-txt-tertiary">— {ver.versionName}</span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-txt-secondary">
                      <span><span className="font-semibold text-txt-primary">{ver.reqCount}</span> yêu cầu</span>
                      {ver.needsReviewCount > 0 && <Badge variant="warning">{ver.needsReviewCount} cần rà soát</Badge>}
                      {ver.approvedCount > 0 && <Badge variant="success">{ver.approvedCount} đã duyệt</Badge>}
                      {ver.highPriorityCount > 0 && <Badge variant="danger">{ver.highPriorityCount} ưu tiên cao</Badge>}
                    </div>
                  </div>
                  <IconChevronRight className="h-4 w-4 text-txt-tertiary shrink-0 group-hover:text-primary transition-colors mr-2" />
                </button>
                <button
                  onClick={(e) => { e.stopPropagation(); onDeleteVersion(ver.id, ver.versionCode + (ver.versionName ? ` — ${ver.versionName}` : "")); }}
                  className="p-3 rounded-r-xl text-txt-tertiary opacity-0 group-hover:opacity-100 hover:text-red-500 hover:bg-red-50 transition-all shrink-0"
                  title="Xóa yêu cầu của phiên bản này"
                >
                  <IconTrashCan className="h-4 w-4" />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Step 3: Requirements List
// ---------------------------------------------------------------------------

function RequirementsListView({
  doc,
  versionCode,
  versionName,
  requirements,
  loading,
  onBack,
  onBackToDoc,
  onGenerate,
  onDeleteVersion,
  loadRequirements,
}: {
  doc: DocSummary | undefined;
  versionCode: string;
  versionName: string;
  requirements: Requirement[];
  loading: boolean;
  onBack: () => void;
  onBackToDoc: () => void;
  onGenerate: () => void;
  onDeleteVersion: () => void;
  loadRequirements: () => void;
}) {
  const [selected, setSelected] = useState<Requirement | null>(null);
  const [localReqs, setLocalReqs] = useState<Requirement[]>(requirements);
  const [deletingOneId, setDeletingOneId] = useState<string | null>(null);
  const [filter, setFilter] = useState<FilterState>({
    search: "",
    requirementType: "",
    reviewStatus: "",
    applicabilityStatus: "",
    priority: "",
  });
  const { toast } = useToast();
  const [commitApprove, isApproving] = useMutation(ApproveMutationNode);
  const [commitDeleteOne] = useMutation(DeleteOneMutationNode);

  useEffect(() => { setLocalReqs(requirements); }, [requirements]);

  const handleSaved = useCallback((updated: Partial<Requirement>) => {
    setLocalReqs((prev) => prev.map((r) => (r.id === selected?.id ? { ...r, ...updated } : r)));
    setSelected((prev) => (prev ? { ...prev, ...updated } : prev));
  }, [selected]);

  // Derive the parseJobId from the first requirement (all reqs in a version share one parse job)
  const parseJobId = localReqs[0]?.parseJobId ?? null;

  const handleApproveAll = useCallback(() => {
    if (!parseJobId) return;
    commitApprove({
      variables: { parseJobId },
      onCompleted: (data: any) => {
        const count: number = data.approveIcpmsRequirementsForParseJob ?? 0;
        toast({ title: `Đã ký duyệt ${count} yêu cầu`, variant: "success" });
        loadRequirements();
      },
      onError: (err: Error) => {
        toast({ title: "Không thể ký duyệt", description: extractError(err), variant: "error" });
      },
    });
  }, [parseJobId, commitApprove, toast, loadRequirements]);

  const handleDeleteOne = useCallback((req: Requirement) => {
    if (!window.confirm(`Xoá yêu cầu "${req.requirementCode}"? Hành động này không thể hoàn tác.`)) return;
    setDeletingOneId(req.id);
    commitDeleteOne({
      variables: { id: req.id },
      onCompleted: () => {
        setDeletingOneId(null);
        toast({ title: "Đã xoá yêu cầu", description: req.requirementCode, variant: "success" });
        if (selected?.id === req.id) setSelected(null);
        setLocalReqs((prev) => prev.filter((r) => r.id !== req.id));
      },
      onError: (err: Error) => {
        setDeletingOneId(null);
        toast({ title: "Không thể xoá", description: extractError(err), variant: "error" });
      },
    });
  }, [commitDeleteOne, toast, selected]);

  const filtered = useMemo(() => {
    return localReqs.filter((r) => {
      if (filter.search) {
        const q = filter.search.toLowerCase();
        if (!r.title.toLowerCase().includes(q) && !r.requirementCode.toLowerCase().includes(q)) return false;
      }
      if (filter.requirementType && r.requirementType !== filter.requirementType) return false;
      if (filter.reviewStatus && r.reviewStatus !== filter.reviewStatus) return false;
      if (filter.applicabilityStatus && r.applicabilityStatus !== filter.applicabilityStatus) return false;
      if (filter.priority && r.priority !== filter.priority) return false;
      return true;
    }).sort((a, b) => a.requirementCode.localeCompare(b.requirementCode, undefined, { numeric: true, sensitivity: "base" }));
  }, [localReqs, filter]);

  const total = localReqs.length;
  const needsReview = localReqs.filter((r) => r.reviewStatus === "NEEDS_REVIEW").length;
  const approved = localReqs.filter((r) => r.reviewStatus === "APPROVED").length;
  const highPriority = localReqs.filter((r) => r.priority === "HIGH").length;
  const aiReviewed = localReqs.filter((r) => r.aiReviewedAt != null).length;
  const notApplicable = localReqs.filter((r) => r.applicabilityStatus === "NOT_APPLICABLE").length;
  const hasFilter = !!(filter.search || filter.requirementType || filter.reviewStatus || filter.applicabilityStatus || filter.priority);

  return (
    <div className="flex flex-col h-full">
      {/* Header + Breadcrumb */}
      <div className="px-6 py-4 border-b border-border-mid shrink-0">
        {/* Breadcrumb */}
        <div className="flex items-center gap-1 text-xs text-txt-tertiary mb-2">
          <button onClick={onBackToDoc} className="hover:text-txt-primary transition-colors">Yêu cầu ICPMS</button>
          <span>/</span>
          <button onClick={onBack} className="hover:text-txt-primary transition-colors max-w-[200px] truncate">{doc?.code} {doc?.title}</button>
          <span>/</span>
          <span className="text-txt-secondary font-medium">{versionCode}{versionName ? ` — ${versionName}` : ""}</span>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button onClick={onBack} className="flex items-center gap-1 text-txt-tertiary hover:text-txt-primary transition-colors">
              <IconChevronLeft className="h-4 w-4" />
            </button>
            <h1 className="text-lg font-semibold text-txt-primary">{versionCode}</h1>
            {versionName && <span className="text-sm text-txt-tertiary">— {versionName}</span>}
          </div>
          <div className="flex items-center gap-2">
            <Button variant="tertiary" onClick={loadRequirements} disabled={loading}>
              <IconRotateCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            </Button>
            <Button variant="tertiary" onClick={onDeleteVersion}>
              <IconTrashCan className="h-4 w-4 mr-1.5" />
              Xóa phiên bản
            </Button>
            {parseJobId && localReqs.length > 0 && (
              <Button
                variant="secondary"
                onClick={handleApproveAll}
                disabled={isApproving}
                title="Ký duyệt tất cả yêu cầu đã được AI rà soát"
              >
                {isApproving ? "Đang ký duyệt..." : "✓ Ký duyệt tất cả"}
              </Button>
            )}
            <Button onClick={onGenerate}>
              <IconPlusLarge className="h-4 w-4 mr-1.5" />
              Tạo từ bản phân tích
            </Button>
          </div>
        </div>
      </div>

      {/* Stats bar */}
      {total > 0 && (
        <div className="flex items-center gap-5 px-6 py-2.5 border-b border-border-mid text-sm shrink-0">
          <div className="flex items-center gap-1.5">
            <span className="text-xl font-bold text-txt-primary">{total}</span>
            <span className="text-txt-tertiary text-xs">yêu cầu</span>
          </div>
          {aiReviewed > 0 && (
            <><div className="h-4 w-px bg-border-mid" /><div className="flex items-center gap-1.5"><Badge variant="info">{aiReviewed}</Badge><span className="text-xs text-txt-tertiary">AI đã rà soát</span></div></>
          )}
          {notApplicable > 0 && (
            <><div className="h-4 w-px bg-border-mid" /><div className="flex items-center gap-1.5"><Badge variant="neutral">{notApplicable}</Badge><span className="text-xs text-txt-tertiary">không áp dụng</span></div></>
          )}
          {needsReview > 0 && (
            <><div className="h-4 w-px bg-border-mid" /><div className="flex items-center gap-1.5"><Badge variant="warning">{needsReview}</Badge><span className="text-xs text-txt-tertiary">cần rà soát</span></div></>
          )}
          {approved > 0 && (
            <><div className="h-4 w-px bg-border-mid" /><div className="flex items-center gap-1.5"><Badge variant="success">{approved}</Badge><span className="text-xs text-txt-tertiary">đã duyệt</span></div></>
          )}
          {highPriority > 0 && (
            <><div className="h-4 w-px bg-border-mid" /><div className="flex items-center gap-1.5"><Badge variant="danger">{highPriority}</Badge><span className="text-xs text-txt-tertiary">ưu tiên cao</span></div></>
          )}
        </div>
      )}

      {/* Filter bar */}
      <div className="flex items-center gap-2.5 px-6 py-3 border-b border-border-mid flex-wrap shrink-0">
        <div className="flex-1 min-w-44 max-w-60">
          <Input variant="bordered" placeholder="Tìm theo tiêu đề, mã..." value={filter.search} onValueChange={(v) => setFilter((f) => ({ ...f, search: v }))} />
        </div>
        <Select value={filter.requirementType || undefined} onValueChange={(v) => setFilter((f) => ({ ...f, requirementType: v as IcpmsRequirementType }))} placeholder="Tất cả loại">
          {(Object.keys(REQ_TYPE_LABELS) as IcpmsRequirementType[]).map((t) => (<Option key={t} value={t}>{REQ_TYPE_LABELS[t]}</Option>))}
        </Select>
        <Select value={filter.reviewStatus || undefined} onValueChange={(v) => setFilter((f) => ({ ...f, reviewStatus: v as IcpmsRequirementReviewStatus }))} placeholder="Tất cả trạng thái">
          {(Object.keys(REVIEW_STATUS_LABELS) as IcpmsRequirementReviewStatus[]).map((s) => (<Option key={s} value={s}>{REVIEW_STATUS_LABELS[s]}</Option>))}
        </Select>
        <Select value={filter.applicabilityStatus || undefined} onValueChange={(v) => setFilter((f) => ({ ...f, applicabilityStatus: v as IcpmsApplicabilityStatus }))} placeholder="Tất cả mức áp dụng">
          {(Object.keys(APPLICABILITY_LABELS) as IcpmsApplicabilityStatus[]).map((s) => (<Option key={s} value={s}>{APPLICABILITY_LABELS[s]}</Option>))}
        </Select>
        <Select value={filter.priority || undefined} onValueChange={(v) => setFilter((f) => ({ ...f, priority: v as IcpmsRequirementPriority }))} placeholder="Tất cả ưu tiên">
          {(Object.keys(PRIORITY_LABELS) as IcpmsRequirementPriority[]).map((p) => (<Option key={p} value={p}>{PRIORITY_LABELS[p]}</Option>))}
        </Select>
        {hasFilter && (
          <Button variant="tertiary" onClick={() => setFilter({ search: "", requirementType: "", reviewStatus: "", applicabilityStatus: "", priority: "" })}>
            <IconCrossLargeX className="h-3 w-3 mr-1" />Xóa bộ lọc
          </Button>
        )}
        {hasFilter && filtered.length !== total && (
          <span className="text-xs text-txt-tertiary ml-auto">{filtered.length} / {total} yêu cầu</span>
        )}
      </div>

      {/* Table */}
      <div className="flex-1 overflow-auto px-6 py-4">
        {loading && localReqs.length === 0 ? (
          <div className="flex items-center justify-center py-16 text-txt-tertiary text-sm">Đang tải dữ liệu...</div>
        ) : filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 gap-2 text-txt-tertiary">
            <span className="text-sm">
              {localReqs.length === 0 ? "Phiên bản này chưa có yêu cầu nào." : "Không có yêu cầu nào khớp với bộ lọc."}
            </span>
            {localReqs.length === 0 && (
              <Button onClick={onGenerate}><IconPlusLarge className="h-4 w-4 mr-1.5" />Tạo từ bản phân tích</Button>
            )}
          </div>
        ) : (
          <Table>
            <Thead>
              <Tr>
                <Th width={48}>STT</Th>
                <Th width={140}>Mã</Th>
                <Th>Yêu cầu</Th>
                <Th width={110}>Nguồn</Th>
                <Th width={120}>Loại</Th>
                <Th width={130}>Trạng thái</Th>
                <Th width={130}>Mức áp dụng</Th>
                <Th width={90}>Ưu tiên</Th>
                <Th width={64}>Điểm</Th>
                <Th width={60}></Th>
              </Tr>
            </Thead>
            <Tbody>
              {filtered.map((req, idx) => (
                <Tr key={req.id} onClick={() => setSelected(req)} className={selected?.id === req.id ? "bg-blue-50" : ""}>
                  <Td noLink><span className="text-xs text-txt-tertiary tabular-nums">{idx + 1}</span></Td>
                  <Td noLink><span className="font-mono text-xs text-txt-tertiary">{req.requirementCode}</span></Td>
                  <Td noLink><span className="text-sm line-clamp-2 text-txt-primary">{req.title}</span></Td>
                  <Td noLink>
                    {req.sourceReference ? (
                      req.sourceSectionSummary ? (
                        <HoverTooltip
                          width={320}
                          trigger={
                            <span className="inline-block bg-blue-50 border border-blue-200 text-blue-700 text-[10px] font-medium px-1.5 py-0.5 rounded leading-tight cursor-default whitespace-nowrap">
                              {req.sourceReference}
                            </span>
                          }
                        >
                          <pre className="whitespace-pre-wrap font-sans leading-relaxed max-h-52 overflow-hidden" style={{ color: "#f9fafb" }}>
                            {req.sourceSectionSummary}
                          </pre>
                        </HoverTooltip>
                      ) : (
                        <span className="inline-block bg-blue-50 border border-blue-200 text-blue-700 text-[10px] font-medium px-1.5 py-0.5 rounded leading-tight cursor-default whitespace-nowrap">
                          {req.sourceReference}
                        </span>
                      )
                    ) : (
                      <span className="text-txt-tertiary text-[10px]">—</span>
                    )}
                  </Td>
                  <Td noLink><span className="text-xs text-txt-secondary">{REQ_TYPE_LABELS[req.requirementType]}</span></Td>
                  <Td noLink><Badge variant={REVIEW_STATUS_VARIANTS[req.reviewStatus]}>{REVIEW_STATUS_LABELS[req.reviewStatus]}</Badge></Td>
                  <Td noLink>
                    {req.applicabilityNote ? (
                      <HoverTooltip
                        width={288}
                        trigger={<Badge variant={APPLICABILITY_VARIANTS[req.applicabilityStatus]}>{APPLICABILITY_LABELS[req.applicabilityStatus]}</Badge>}
                      >
                        <p className="text-[10px] font-semibold uppercase tracking-wide mb-1" style={{ color: "#9ca3af" }}>Nhận xét AI</p>
                        <p className="leading-relaxed" style={{ color: "#f9fafb" }}>{req.applicabilityNote}</p>
                      </HoverTooltip>
                    ) : (
                      <Badge variant={APPLICABILITY_VARIANTS[req.applicabilityStatus]}>{APPLICABILITY_LABELS[req.applicabilityStatus]}</Badge>
                    )}
                  </Td>
                  <Td noLink><Badge variant={PRIORITY_VARIANTS[req.priority]}>{PRIORITY_LABELS[req.priority]}</Badge></Td>
                  <Td noLink><span className="text-xs font-mono text-txt-tertiary">{req.candidateScore}</span></Td>
                  <Td noLink>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleDeleteOne(req); }}
                      disabled={deletingOneId === req.id}
                      className="p-1 rounded text-txt-tertiary hover:text-red-500 hover:bg-red-50 transition-all disabled:opacity-40"
                      title="Xoá yêu cầu này"
                    >
                      <IconTrashCan className="h-3.5 w-3.5" />
                    </button>
                  </Td>
                </Tr>
              ))}
            </Tbody>
          </Table>
        )}
      </div>

      {selected && <RequirementDetailPanel req={selected} onClose={() => setSelected(null)} onSaved={handleSaved} />}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main Page
// ---------------------------------------------------------------------------

export function IcpmsRequirementsPage() {
  usePageTitle("Yêu cầu ICPMS");
  const organizationId = useOrganizationId();
  const environment = useRelayEnvironment();
  const { toast } = useToast();
  const [searchParams, setSearchParams] = useSearchParams();

  const selectedDocId = searchParams.get("docId") ?? "";
  const selectedVerId = searchParams.get("verId") ?? "";

  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [loading, setLoading] = useState(false);
  const [showGenerate, setShowGenerate] = useState(false);

  // Versions for step 2 (fetched when doc selected)
  const [versions, setVersions] = useState<VersionOpt[]>([]);
  const [versionsLoading, setVersionsLoading] = useState(false);

  const loadRequirements = useCallback(() => {
    if (!organizationId) return;
    setLoading(true);
    (fetchQuery(environment, ListQueryNode, { organizationId }, { networkCacheConfig: { force: true } }) as any)
      .toPromise()
      .then((data: any) => {
        setRequirements([...data.icpmsRequirementsForOrganization]);
      })
      .catch((err: Error) => {
        toast({ title: "Không thể tải yêu cầu", description: extractError(err), variant: "error" });
      })
      .finally(() => setLoading(false));
  }, [organizationId, environment, toast]);

  useEffect(() => { loadRequirements(); }, [loadRequirements]);

  // Fetch versions when a doc is selected (step 2)
  useEffect(() => {
    if (!selectedDocId) { setVersions([]); return; }
    setVersionsLoading(true);
    fetchQuery(environment, VersionsQueryNode, { documentId: selectedDocId }).subscribe({
      next: (data: unknown) => {
        const d = data as IcpmsDocumentVersionsTabQuery$data;
        if (d.document.__typename === "IcpmsDocument") {
          const edges = (d.document as any).versions?.edges ?? [];
          setVersions(edges.map((e: any) => e.node as VersionOpt));
        }
        setVersionsLoading(false);
      },
      error: () => setVersionsLoading(false),
    });
  }, [environment, selectedDocId]);

  // Derive document summaries from requirements
  const docSummaries = useMemo((): DocSummary[] => {
    const map = new Map<string, DocSummary>();
    for (const r of requirements) {
      if (!r.document) continue;
      const existing = map.get(r.document.id) ?? {
        id: r.document.id,
        code: (r.document as any).code ?? "",
        title: r.document.title,
        versionCount: 0,
        reqCount: 0,
        approvedCount: 0,
        needsReviewCount: 0,
        highPriorityCount: 0,
        _versionIds: new Set<string>(),
      } as DocSummary & { _versionIds: Set<string> };
      (existing as any)._versionIds.add(r.documentVersionId);
      existing.versionCount = (existing as any)._versionIds.size;
      existing.reqCount++;
      if (r.reviewStatus === "APPROVED") existing.approvedCount++;
      if (r.reviewStatus === "NEEDS_REVIEW") existing.needsReviewCount++;
      if (r.priority === "HIGH") existing.highPriorityCount++;
      map.set(r.document.id, existing);
    }
    return Array.from(map.values()).sort((a, b) => a.code.localeCompare(b.code));
  }, [requirements]);

  // Derive version summaries for selected doc
  const versionSummaries = useMemo((): VersionSummary[] => {
    const versionReqs = requirements.filter((r) => r.document?.id === selectedDocId);
    const map = new Map<string, VersionSummary>();
    for (const r of versionReqs) {
      const existing = map.get(r.documentVersionId) ?? {
        id: r.documentVersionId,
        versionCode: "",
        versionName: "",
        reqCount: 0,
        approvedCount: 0,
        needsReviewCount: 0,
        highPriorityCount: 0,
      };
      existing.reqCount++;
      if (r.reviewStatus === "APPROVED") existing.approvedCount++;
      if (r.reviewStatus === "NEEDS_REVIEW") existing.needsReviewCount++;
      if (r.priority === "HIGH") existing.highPriorityCount++;
      map.set(r.documentVersionId, existing);
    }
    // Fill in version code/name from fetched versions
    for (const v of versions) {
      const s = map.get(v.id);
      if (s) { s.versionCode = v.versionCode; s.versionName = v.versionName; }
    }
    return Array.from(map.values()).sort((a, b) => b.versionCode.localeCompare(a.versionCode));
  }, [requirements, selectedDocId, versions]);

  // Requirements for the selected version
  const versionRequirements = useMemo(() => {
    if (!selectedVerId) return [];
    return requirements.filter((r) => r.documentVersionId === selectedVerId);
  }, [requirements, selectedVerId]);

  // Delete mutations
  const [commitDeleteDoc, isDeletingDoc] = useMutation(DeleteDocMutationNode);
  const [commitDeleteVersion, isDeletingVersion] = useMutation(DeleteVersionMutationNode);
  const [confirmDelete, setConfirmDelete] = useState<{ type: "doc" | "version"; id: string; label: string } | null>(null);

  const handleDeleteDoc = useCallback((docId: string, label: string) => {
    setConfirmDelete({ type: "doc", id: docId, label });
  }, []);

  const handleDeleteVersion = useCallback((verId: string, label: string) => {
    setConfirmDelete({ type: "version", id: verId, label });
  }, []);

  const handleConfirmDelete = useCallback(() => {
    if (!confirmDelete) return;
    const { type, id } = confirmDelete;
    setConfirmDelete(null);
    if (type === "doc") {
      commitDeleteDoc({
        variables: { documentId: id },
        onCompleted: (data: unknown) => {
          const n = (data as any).deleteIcpmsRequirementsForDocument ?? 0;
          toast({ title: "Đã xóa", description: `Đã xóa ${n} yêu cầu của tài liệu`, variant: "success" });
          loadRequirements();
          setSearchParams({});
        },
        onError: (err) => toast({ title: "Lỗi", description: extractError(err), variant: "error" }),
      });
    } else {
      commitDeleteVersion({
        variables: { documentVersionId: id },
        onCompleted: (data: unknown) => {
          const n = (data as any).deleteIcpmsRequirementsForVersion ?? 0;
          toast({ title: "Đã xóa", description: `Đã xóa ${n} yêu cầu của phiên bản`, variant: "success" });
          loadRequirements();
          if (selectedVerId === id) setSearchParams({ docId: selectedDocId });
        },
        onError: (err) => toast({ title: "Lỗi", description: extractError(err), variant: "error" }),
      });
    }
  }, [confirmDelete, commitDeleteDoc, commitDeleteVersion, toast, loadRequirements, setSearchParams, selectedDocId, selectedVerId]);

  // Navigation helpers
  const selectDoc = (docId: string) => setSearchParams({ docId });
  const selectVer = (verId: string) => setSearchParams({ docId: selectedDocId, verId });
  const goBack = () => {
    if (selectedVerId) setSearchParams({ docId: selectedDocId });
    else setSearchParams({});
  };
  const goToRoot = () => setSearchParams({});

  const currentDoc = docSummaries.find((d) => d.id === selectedDocId);
  const currentVer = versions.find((v) => v.id === selectedVerId);

  const isDeleting = isDeletingDoc || isDeletingVersion;

  // Render based on navigation state
  if (selectedVerId) {
    return (
      <>
        <RequirementsListView
          doc={currentDoc}
          versionCode={currentVer?.versionCode ?? selectedVerId}
          versionName={currentVer?.versionName ?? ""}
          requirements={versionRequirements}
          loading={loading}
          onBack={goBack}
          onBackToDoc={goToRoot}
          onGenerate={() => setShowGenerate(true)}
          onDeleteVersion={() => handleDeleteVersion(selectedVerId, currentVer?.versionCode ?? selectedVerId)}
          loadRequirements={loadRequirements}
        />
        {showGenerate && (
          <GenerateDialog
            onClose={() => setShowGenerate(false)}
            onGenerated={loadRequirements}
            preselectedDocId={selectedDocId}
            preselectedVerId={selectedVerId}
          />
        )}
        {confirmDelete && (
          <ConfirmDeleteDialog
            label={confirmDelete.label}
            type={confirmDelete.type}
            onConfirm={handleConfirmDelete}
            onCancel={() => setConfirmDelete(null)}
            loading={isDeleting}
          />
        )}
      </>
    );
  }

  if (selectedDocId) {
    return (
      <>
        <VersionPickerView
          doc={currentDoc}
          versions={versionsLoading ? [] : versionSummaries}
          loading={versionsLoading}
          onSelect={selectVer}
          onBack={goBack}
          onGenerate={() => setShowGenerate(true)}
          onDeleteDoc={() => handleDeleteDoc(selectedDocId, currentDoc?.title ?? selectedDocId)}
          onDeleteVersion={handleDeleteVersion}
        />
        {showGenerate && (
          <GenerateDialog
            onClose={() => setShowGenerate(false)}
            onGenerated={loadRequirements}
            preselectedDocId={selectedDocId}
          />
        )}
        {confirmDelete && (
          <ConfirmDeleteDialog
            label={confirmDelete.label}
            type={confirmDelete.type}
            onConfirm={handleConfirmDelete}
            onCancel={() => setConfirmDelete(null)}
            loading={isDeleting}
          />
        )}
      </>
    );
  }

  return (
    <>
      <DocumentPickerView
        docs={docSummaries}
        loading={loading}
        onSelect={selectDoc}
        onRefresh={loadRequirements}
        onGenerate={() => setShowGenerate(true)}
        onDeleteDoc={handleDeleteDoc}
      />
      {showGenerate && (
        <GenerateDialog
          onClose={() => setShowGenerate(false)}
          onGenerated={loadRequirements}
        />
      )}
      {confirmDelete && (
        <ConfirmDeleteDialog
          label={confirmDelete.label}
          type={confirmDelete.type}
          onConfirm={handleConfirmDelete}
          onCancel={() => setConfirmDelete(null)}
          loading={isDeleting}
        />
      )}
    </>
  );
}