-- Copyright (c) 2025-2026 VATM ICPMS <sms@vatm.vn>.
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted, provided that the above
-- copyright notice and this permission notice appear in all copies.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
-- REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
-- AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
-- INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
-- LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
-- OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
-- PERFORMANCE OF THIS SOFTWARE.

ALTER TABLE emails ADD COLUMN recipient_name TEXT NOT NULL;
ALTER TABLE emails RENAME COLUMN email_address_to TO recipient_email;

ALTER TABLE emails ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE emails ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE emails ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE emails ALTER COLUMN updated_at SET NOT NULL;
