CREATE TABLE IF NOT EXISTS icpms_document_versions (
    tenant_id text NOT NULL,
    id text NOT NULL,
    organization_id text NOT NULL,
    document_id text NOT NULL,
    version_code text NOT NULL,
    version_name text NOT NULL,
    edition text,
    amendment text,
    version_number text,
    publication_date timestamp with time zone,
    effective_date timestamp with time zone,
    expiry_date timestamp with time zone,
    supersedes_version_id text,
    superseded_by_version_id text,
    superseded_date timestamp with time zone,
    status text NOT NULL,
    is_current boolean NOT NULL DEFAULT false,
    change_summary text,
    notes text,
    raw_file_status text NOT NULL DEFAULT 'NOT_UPLOADED',
    created_by text NOT NULL,
    updated_by text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,

    PRIMARY KEY (id),
    CONSTRAINT fk_icpms_document_versions_document_id FOREIGN KEY (document_id) REFERENCES icpms_documents(id) ON DELETE CASCADE,
    CONSTRAINT uk_icpms_document_versions_version_code UNIQUE (document_id, version_code)
);
