-- Copyright (c) 2026 VATM ICPMS <sms@vatm.vn>.
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted, provided that the above
-- copyright notice and this permission notice appear in all copies.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
-- REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
-- AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
-- INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
-- LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
-- OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
-- PERFORMANCE OF THIS SOFTWARE.

ALTER TABLE emails
ADD COLUMN status TEXT NOT NULL DEFAULT 'PENDING',
ADD COLUMN processing_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 10,
ADD COLUMN last_attempted_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN last_error TEXT;

UPDATE emails SET status = 'SENT' WHERE sent_at IS NOT NULL;

CREATE INDEX idx_emails_pending ON emails (status, created_at)
WHERE status = 'PENDING';
