/**
 * @generated SignedSource<<85a947ce3e05b5b979f06ea474d0a8c0>>
 * @lightSyntaxTransform
 * @nogrep
 */

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

import { ConcreteRequest } from 'relay-runtime';
export type IcpmsApplicabilityStatus = "APPLICABLE" | "NEEDS_REVIEW" | "NOT_APPLICABLE" | "PARTIALLY_APPLICABLE" | "UNKNOWN";
export type IcpmsRequirementPriority = "HIGH" | "LOW" | "MEDIUM";
export type IcpmsRequirementReviewStatus = "APPROVED" | "ARCHIVED" | "CANDIDATE" | "NEEDS_REVIEW" | "REJECTED" | "REVIEWED";
export type IcpmsRequirementType = "EVIDENCE" | "INFORMATION" | "MONITORING" | "OBLIGATION" | "OTHER" | "PROCESS" | "PROHIBITION" | "RECORD" | "REPORTING" | "RESPONSIBILITY" | "REVIEW" | "TRAINING";
export type IcpmsRequirementsPageListQuery$variables = {
  organizationId: string;
};
export type IcpmsRequirementsPageListQuery$data = {
  readonly icpmsRequirementsForOrganization: ReadonlyArray<{
    readonly aiReviewedAt: string | null | undefined;
    readonly applicabilityNote: string | null | undefined;
    readonly applicabilityStatus: IcpmsApplicabilityStatus;
    readonly candidateScore: number;
    readonly createdAt: string;
    readonly description: string | null | undefined;
    readonly document: {
      readonly code: string;
      readonly id: string;
      readonly title: string;
    };
    readonly documentId: string;
    readonly documentVersionId: string;
    readonly id: string;
    readonly isAutoGenerated: boolean;
    readonly organizationId: string;
    readonly parseJobId: string;
    readonly priority: IcpmsRequirementPriority;
    readonly requirementCode: string;
    readonly requirementType: IcpmsRequirementType;
    readonly reviewStatus: IcpmsRequirementReviewStatus;
    readonly sourceReference: string | null | undefined;
    readonly sourceSectionId: string | null | undefined;
    readonly sourceSectionSummary: string | null | undefined;
    readonly title: string;
    readonly updatedAt: string;
  }>;
};
export type IcpmsRequirementsPageListQuery = {
  response: IcpmsRequirementsPageListQuery$data;
  variables: IcpmsRequirementsPageListQuery$variables;
};

const node: ConcreteRequest = (function(){
var v0 = [
  {
    "defaultValue": null,
    "kind": "LocalArgument",
    "name": "organizationId"
  }
],
v1 = {
  "alias": null,
  "args": null,
  "kind": "ScalarField",
  "name": "id",
  "storageKey": null
},
v2 = {
  "alias": null,
  "args": null,
  "kind": "ScalarField",
  "name": "title",
  "storageKey": null
},
v3 = [
  {
    "alias": null,
    "args": [
      {
        "kind": "Variable",
        "name": "organizationId",
        "variableName": "organizationId"
      }
    ],
    "concreteType": "IcpmsRequirement",
    "kind": "LinkedField",
    "name": "icpmsRequirementsForOrganization",
    "plural": true,
    "selections": [
      (v1/*: any*/),
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "organizationId",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "documentId",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "concreteType": "IcpmsDocument",
        "kind": "LinkedField",
        "name": "document",
        "plural": false,
        "selections": [
          (v1/*: any*/),
          {
            "alias": null,
            "args": null,
            "kind": "ScalarField",
            "name": "code",
            "storageKey": null
          },
          (v2/*: any*/)
        ],
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "documentVersionId",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "parseJobId",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "sourceSectionId",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "sourceReference",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "sourceSectionSummary",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "requirementCode",
        "storageKey": null
      },
      (v2/*: any*/),
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "description",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "requirementType",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "applicabilityStatus",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "applicabilityNote",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "reviewStatus",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "priority",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "candidateScore",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "isAutoGenerated",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "aiReviewedAt",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "createdAt",
        "storageKey": null
      },
      {
        "alias": null,
        "args": null,
        "kind": "ScalarField",
        "name": "updatedAt",
        "storageKey": null
      }
    ],
    "storageKey": null
  }
];
return {
  "fragment": {
    "argumentDefinitions": (v0/*: any*/),
    "kind": "Fragment",
    "metadata": null,
    "name": "IcpmsRequirementsPageListQuery",
    "selections": (v3/*: any*/),
    "type": "Query",
    "abstractKey": null
  },
  "kind": "Request",
  "operation": {
    "argumentDefinitions": (v0/*: any*/),
    "kind": "Operation",
    "name": "IcpmsRequirementsPageListQuery",
    "selections": (v3/*: any*/)
  },
  "params": {
    "cacheID": "0547863d9b97e4a37b71a846f1eb385c",
    "id": null,
    "metadata": {},
    "name": "IcpmsRequirementsPageListQuery",
    "operationKind": "query",
    "text": "query IcpmsRequirementsPageListQuery(\n  $organizationId: ID!\n) {\n  icpmsRequirementsForOrganization(organizationId: $organizationId) {\n    id\n    organizationId\n    documentId\n    document {\n      id\n      code\n      title\n    }\n    documentVersionId\n    parseJobId\n    sourceSectionId\n    sourceReference\n    sourceSectionSummary\n    requirementCode\n    title\n    description\n    requirementType\n    applicabilityStatus\n    applicabilityNote\n    reviewStatus\n    priority\n    candidateScore\n    isAutoGenerated\n    aiReviewedAt\n    createdAt\n    updatedAt\n  }\n}\n"
  }
};
})();

(node as any).hash = "a85002e25ec0a9dda4836e88ae60f8ed";

export default node;
