// Copyright (c) 2026 VATM ICPMS <sms@vatm.vn>.

package coredata

import (
	"time"

	"go.probo.inc/probo/pkg/gid"
)

type (
	IcpmsRequirement struct {
		ID                  gid.GID                      `db:"id"`
		TenantID            gid.TenantID                 `db:"tenant_id"`
		OrganizationID      gid.GID                      `db:"organization_id"`
		DocumentID          gid.GID                      `db:"document_id"`
		DocumentVersionID   gid.GID                      `db:"document_version_id"`
		ParseJobID          gid.GID                      `db:"parse_job_id"`
		SourceSectionID     *gid.GID                     `db:"source_section_id"`
		RequirementCode     string                       `db:"requirement_code"`
		Title               string                       `db:"title"`
		Description         *string                      `db:"description"`
		RequirementType     IcpmsRequirementType         `db:"requirement_type"`
		ApplicabilityStatus IcpmsApplicabilityStatus     `db:"applicability_status"`
		ReviewStatus        IcpmsRequirementReviewStatus `db:"review_status"`
		Priority            IcpmsRequirementPriority     `db:"priority"`
		CandidateScore      int                          `db:"candidate_score"`
		KeywordMatches      *string                      `db:"keyword_matches"`
		IsAutoGenerated     bool                         `db:"is_auto_generated"`
		IsDeleted           bool                         `db:"is_deleted"`
		CreatedBy           *gid.GID                     `db:"created_by"`
		CreatedAt           time.Time                    `db:"created_at"`
		UpdatedAt           time.Time                    `db:"updated_at"`
	}

	IcpmsRequirements []*IcpmsRequirement
)

func (r *IcpmsRequirement) GetID() gid.GID { return r.ID }
func (IcpmsRequirement) IsNode()           {}
