package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/cookiebanner"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// CookieBanner is the resolver for the cookieBanner field.
func (r *cookieConsentRecordResolver) CookieBanner(ctx context.Context, obj *types.CookieConsentRecord) (*types.CookieBanner, error) {
	if _, err := r.authorize(ctx, obj.CookieBanner.ID, probo.ActionCookieBannerGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	banner, err := loaders.CookieBanner.Load(ctx, obj.CookieBanner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot get cookie banner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewCookieBanner(banner), nil
}

// CookieBannerVersion is the resolver for the cookieBannerVersion field.
func (r *cookieConsentRecordResolver) CookieBannerVersion(ctx context.Context, obj *types.CookieConsentRecord) (*types.CookieBannerVersion, error) {
	scope, err := r.authorize(ctx, obj.CookieBannerVersion.ID, probo.ActionCookieBannerVersionGet)
	if err != nil {
		return nil, err
	}

	version, err := r.cookieBanner.GetCookieBannerVersion(ctx, scope, obj.CookieBannerVersion.ID)
	if err != nil {
		if errors.Is(err, cookiebanner.ErrVersionNotFound) {
			return nil, nil
		}

		r.logger.ErrorCtx(ctx, "cannot get cookie banner version", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CookieBannerVersion{
		ID:        version.ID,
		Version:   version.Version,
		State:     string(version.State),
		CreatedAt: version.CreatedAt,
		UpdatedAt: version.UpdatedAt,
	}, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *cookieConsentRecordConnectionResolver) TotalCount(ctx context.Context, obj *types.CookieConsentRecordConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionCookieConsentRecordList)
	if err != nil {
		return 0, err
	}

	count, err := r.cookieBanner.CountCookieConsentRecordsForBanner(ctx, scope, obj.ParentID, obj.Filter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count consent records", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CookieConsentRecord returns schema.CookieConsentRecordResolver implementation.
func (r *Resolver) CookieConsentRecord() schema.CookieConsentRecordResolver {
	return &cookieConsentRecordResolver{r}
}

// CookieConsentRecordConnection returns schema.CookieConsentRecordConnectionResolver implementation.
func (r *Resolver) CookieConsentRecordConnection() schema.CookieConsentRecordConnectionResolver {
	return &cookieConsentRecordConnectionResolver{r}
}

type cookieConsentRecordResolver struct{ *Resolver }
type cookieConsentRecordConnectionResolver struct{ *Resolver }
