package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// Organization is the resolver for the organization field.
func (r *icpmsChecklistResolver) Organization(ctx context.Context, obj *coredata.IcpmsChecklist) (*types.Organization, error) {
	return &types.Organization{ID: obj.OrganizationID}, nil
}

// Document is the resolver for the document field.
func (r *icpmsChecklistResolver) Document(ctx context.Context, obj *coredata.IcpmsChecklist) (*types.IcpmsDocument, error) {
	doc, err := r.probo.IcpmsDocuments.Get(ctx, coredata.NewScope(obj.TenantID), obj.DocumentID)
	if err != nil {
		return nil, err
	}
	return types.NewIcpmsDocument(doc), nil
}

// DocumentVersion is the resolver for the documentVersion field.
func (r *icpmsChecklistResolver) DocumentVersion(ctx context.Context, obj *coredata.IcpmsChecklist) (*types.IcpmsDocumentVersion, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScope(obj.TenantID), obj.DocumentVersionID)
	if err != nil {
		return nil, err
	}
	return types.NewIcpmsDocumentVersion(version), nil
}

// Requirement is the resolver for the requirement field.
func (r *icpmsChecklistResolver) Requirement(ctx context.Context, obj *coredata.IcpmsChecklist) (*coredata.IcpmsRequirement, error) {
	if obj.RequirementID == nil {
		return nil, nil
	}
	scope := coredata.NewScope(obj.TenantID)
	return r.probo.IcpmsRequirements.Get(ctx, scope, *obj.RequirementID)
}

// Status is the resolver for the status field.
func (r *icpmsChecklistResolver) Status(ctx context.Context, obj *coredata.IcpmsChecklist) (types.IcpmsChecklistStatus, error) {
	return types.IcpmsChecklistStatus(obj.Status), nil
}

// ApprovalStatus is the resolver for the approvalStatus field.
func (r *icpmsChecklistResolver) ApprovalStatus(ctx context.Context, obj *coredata.IcpmsChecklist) (types.IcpmsChecklistApprovalStatus, error) {
	return types.IcpmsChecklistApprovalStatus(obj.ApprovalStatus), nil
}

// CreatedFrom is the resolver for the createdFrom field.
func (r *icpmsChecklistResolver) CreatedFrom(ctx context.Context, obj *coredata.IcpmsChecklist) (types.IcpmsChecklistCreatedFrom, error) {
	return types.IcpmsChecklistCreatedFrom(obj.CreatedFrom), nil
}

// CreatedByID is the resolver for the createdById field.
func (r *icpmsChecklistResolver) CreatedByID(ctx context.Context, obj *coredata.IcpmsChecklist) (*gid.GID, error) {
	return obj.CreatedBy, nil
}

// ApprovedByID is the resolver for the approvedById field.
func (r *icpmsChecklistResolver) ApprovedByID(ctx context.Context, obj *coredata.IcpmsChecklist) (*gid.GID, error) {
	return obj.ApprovedBy, nil
}

// RejectedByID is the resolver for the rejectedById field.
func (r *icpmsChecklistResolver) RejectedByID(ctx context.Context, obj *coredata.IcpmsChecklist) (*gid.GID, error) {
	return obj.RejectedBy, nil
}

// CreateIcpmsChecklist is the resolver for the createIcpmsChecklist field.
func (r *mutationResolver) CreateIcpmsChecklist(ctx context.Context, input types.CreateIcpmsChecklistInput) (*types.CreateIcpmsChecklistPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionOrganizationUpdate)
	if err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)

	item := &coredata.IcpmsChecklist{
		OrganizationID:       input.OrganizationID,
		DocumentID:           input.DocumentID,
		DocumentVersionID:    input.DocumentVersionID,
		RequirementID:        input.RequirementID,
		ChecklistQuestion:    input.ChecklistQuestion,
		SourceReference:      input.SourceReference,
		ImplementationMethod: input.ImplementationMethod,
		ResponsibleUnit:      input.ResponsibleUnit,
		ResponsibleRole:      input.ResponsibleRole,
		RequiredEvidence:     input.RequiredEvidence,
		CurrentStatusText:    input.CurrentStatusText,
		ActionPlan:           input.ActionPlan,
		RiskIfNotComplied:    input.RiskIfNotComplied,
		ComplianceDomain:     input.ComplianceDomain,
		Frequency:            input.Frequency,
		DueDays:              input.DueDays,
		CreatedFrom:          coredata.IcpmsChecklistCreatedFromManual,
		CreatedBy:            &identity.ID,
	}

	if input.Priority != nil {
		item.Priority = *input.Priority
	}

	if err := r.probo.IcpmsChecklists.Create(ctx, scope, item); err != nil {
		return nil, fmt.Errorf("cannot create checklist: %w", err)
	}

	return &types.CreateIcpmsChecklistPayload{Checklist: item}, nil
}

// CreateIcpmsChecklistFromAiSuggestion is the resolver for the createIcpmsChecklistFromAiSuggestion field.
func (r *mutationResolver) CreateIcpmsChecklistFromAiSuggestion(ctx context.Context, input types.CreateIcpmsChecklistFromAiSuggestionInput) (*types.CreateIcpmsChecklistFromAiSuggestionPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.AiReviewSuggestionID)
	identity := authn.IdentityFromContext(ctx)

	sug, err := r.probo.IcpmsAiReviews.GetSuggestion(ctx, scope, input.AiReviewSuggestionID)
	if err != nil {
		return nil, fmt.Errorf("cannot load suggestion: %w", err)
	}

	checklist, isNew, err := r.probo.IcpmsChecklists.CreateFromAiSuggestion(ctx, scope, sug, identity.ID, "CL")
	if err != nil {
		return nil, fmt.Errorf("cannot create checklist from suggestion: %w", err)
	}

	return &types.CreateIcpmsChecklistFromAiSuggestionPayload{
		Checklist:   checklist,
		WasExisting: !isNew,
	}, nil
}

// CreateIcpmsChecklistsFromAiSuggestions is the resolver for the createIcpmsChecklistsFromAiSuggestions field.
func (r *mutationResolver) CreateIcpmsChecklistsFromAiSuggestions(ctx context.Context, input types.CreateIcpmsChecklistsFromAiSuggestionsInput) (*types.CreateIcpmsChecklistsFromAiSuggestionsPayload, error) {
	identity := authn.IdentityFromContext(ctx)

	var checklists []*coredata.IcpmsChecklist
	createdCount := 0
	existingCount := 0

	for _, sugID := range input.AiReviewSuggestionIds {
		scope := coredata.NewScopeFromObjectID(sugID)

		sug, err := r.probo.IcpmsAiReviews.GetSuggestion(ctx, scope, sugID)
		if err != nil {
			return nil, fmt.Errorf("cannot load suggestion %s: %w", sugID.String(), err)
		}

		checklist, isNew, err := r.probo.IcpmsChecklists.CreateFromAiSuggestion(ctx, scope, sug, identity.ID, "CL")
		if err != nil {
			return nil, fmt.Errorf("cannot create checklist from suggestion %s: %w", sugID.String(), err)
		}

		checklists = append(checklists, checklist)
		if isNew {
			createdCount++
		} else {
			existingCount++
		}
	}

	return &types.CreateIcpmsChecklistsFromAiSuggestionsPayload{
		Checklists:    checklists,
		CreatedCount:  createdCount,
		ExistingCount: existingCount,
	}, nil
}

// UpdateIcpmsChecklist is the resolver for the updateIcpmsChecklist field.
func (r *mutationResolver) UpdateIcpmsChecklist(ctx context.Context, input types.UpdateIcpmsChecklistInput) (*types.UpdateIcpmsChecklistPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)

	item, err := r.probo.IcpmsChecklists.Get(ctx, scope, input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot load checklist: %w", err)
	}

	if input.ChecklistQuestion != nil {
		item.ChecklistQuestion = *input.ChecklistQuestion
	}
	if input.ImplementationMethod != nil {
		item.ImplementationMethod = input.ImplementationMethod
	}
	if input.ResponsibleUnit != nil {
		item.ResponsibleUnit = input.ResponsibleUnit
	}
	if input.ResponsibleRole != nil {
		item.ResponsibleRole = input.ResponsibleRole
	}
	if input.RequiredEvidence != nil {
		item.RequiredEvidence = input.RequiredEvidence
	}
	if input.CurrentStatusText != nil {
		item.CurrentStatusText = input.CurrentStatusText
	}
	if input.ActionPlan != nil {
		item.ActionPlan = input.ActionPlan
	}
	if input.RiskIfNotComplied != nil {
		item.RiskIfNotComplied = input.RiskIfNotComplied
	}
	if input.Priority != nil {
		item.Priority = *input.Priority
	}
	if input.ComplianceDomain != nil {
		item.ComplianceDomain = input.ComplianceDomain
	}
	if input.Frequency != nil {
		item.Frequency = input.Frequency
	}
	if input.DueDays != nil {
		item.DueDays = input.DueDays
	}
	if input.SourceReference != nil {
		item.SourceReference = input.SourceReference
	}

	if err := r.probo.IcpmsChecklists.Update(ctx, scope, item); err != nil {
		return nil, fmt.Errorf("cannot update checklist: %w", err)
	}

	return &types.UpdateIcpmsChecklistPayload{Checklist: item}, nil
}

// ApproveIcpmsChecklist is the resolver for the approveIcpmsChecklist field.
func (r *mutationResolver) ApproveIcpmsChecklist(ctx context.Context, input types.ApproveIcpmsChecklistInput) (*types.ApproveIcpmsChecklistPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)
	identity := authn.IdentityFromContext(ctx)

	item, err := r.probo.IcpmsChecklists.Approve(ctx, scope, input.ID, identity.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot approve checklist: %w", err)
	}

	return &types.ApproveIcpmsChecklistPayload{Checklist: item}, nil
}

// RejectIcpmsChecklist is the resolver for the rejectIcpmsChecklist field.
func (r *mutationResolver) RejectIcpmsChecklist(ctx context.Context, input types.RejectIcpmsChecklistInput) (*types.RejectIcpmsChecklistPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)
	identity := authn.IdentityFromContext(ctx)

	item, err := r.probo.IcpmsChecklists.Reject(ctx, scope, input.ID, identity.ID, input.RejectionReason)
	if err != nil {
		return nil, fmt.Errorf("cannot reject checklist: %w", err)
	}

	return &types.RejectIcpmsChecklistPayload{Checklist: item}, nil
}

// RequestIcpmsChecklistRevision is the resolver for the requestIcpmsChecklistRevision field.
func (r *mutationResolver) RequestIcpmsChecklistRevision(ctx context.Context, input types.RequestIcpmsChecklistRevisionInput) (*types.RequestIcpmsChecklistRevisionPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)

	item, err := r.probo.IcpmsChecklists.RequestRevision(ctx, scope, input.ID, input.Reason)
	if err != nil {
		return nil, fmt.Errorf("cannot request revision: %w", err)
	}

	return &types.RequestIcpmsChecklistRevisionPayload{Checklist: item}, nil
}

// ArchiveIcpmsChecklist is the resolver for the archiveIcpmsChecklist field.
func (r *mutationResolver) ArchiveIcpmsChecklist(ctx context.Context, input types.ArchiveIcpmsChecklistInput) (*types.ArchiveIcpmsChecklistPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)

	item, err := r.probo.IcpmsChecklists.Archive(ctx, scope, input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot archive checklist: %w", err)
	}

	return &types.ArchiveIcpmsChecklistPayload{Checklist: item}, nil
}

// DeleteIcpmsChecklist is the resolver for the deleteIcpmsChecklist field.
func (r *mutationResolver) DeleteIcpmsChecklist(ctx context.Context, input types.DeleteIcpmsChecklistInput) (*types.DeleteIcpmsChecklistPayload, error) {
	scope := coredata.NewScopeFromObjectID(input.ID)

	if err := r.probo.IcpmsChecklists.Delete(ctx, scope, input.ID); err != nil {
		return nil, fmt.Errorf("cannot delete checklist: %w", err)
	}

	return &types.DeleteIcpmsChecklistPayload{DeletedChecklistID: input.ID}, nil
}

// IcpmsChecklists is the resolver for the icpmsChecklists field.
func (r *queryResolver) IcpmsChecklists(ctx context.Context, organizationID gid.GID, filter *types.IcpmsChecklistFilter) (*types.IcpmsChecklistConnection, error) {
	scope := coredata.NewScopeFromObjectID(organizationID)

	items, err := r.probo.IcpmsChecklists.ListForOrganization(ctx, scope, organizationID)
	if err != nil {
		return nil, fmt.Errorf("cannot list checklists: %w", err)
	}

	edges := make([]*types.IcpmsChecklistEdge, len(items))
	for i, item := range items {
		edges[i] = &types.IcpmsChecklistEdge{Node: item}
	}

	return &types.IcpmsChecklistConnection{
		Edges:      edges,
		TotalCount: len(items),
		PageInfo:   &types.PageInfo{},
	}, nil
}

// IcpmsChecklist is the resolver for the icpmsChecklist field.
func (r *queryResolver) IcpmsChecklist(ctx context.Context, id gid.GID) (*coredata.IcpmsChecklist, error) {
	scope := coredata.NewScope(id.TenantID())
	return r.probo.IcpmsChecklists.Get(ctx, scope, id)
}

// IcpmsChecklistsByRequirement is the resolver for the icpmsChecklistsByRequirement field.
func (r *queryResolver) IcpmsChecklistsByRequirement(ctx context.Context, requirementID gid.GID) (*types.IcpmsChecklistConnection, error) {
	scope := coredata.NewScope(requirementID.TenantID())

	items, err := r.probo.IcpmsChecklists.ListForRequirement(ctx, scope, requirementID)
	if err != nil {
		return nil, fmt.Errorf("cannot list checklists by requirement: %w", err)
	}

	edges := make([]*types.IcpmsChecklistEdge, len(items))
	for i, item := range items {
		edges[i] = &types.IcpmsChecklistEdge{Node: item}
	}

	return &types.IcpmsChecklistConnection{
		Edges:      edges,
		TotalCount: len(items),
		PageInfo:   &types.PageInfo{},
	}, nil
}

// IcpmsChecklistsByDocument is the resolver for the icpmsChecklistsByDocument field.
func (r *queryResolver) IcpmsChecklistsByDocument(ctx context.Context, documentID gid.GID, documentVersionID *gid.GID) (*types.IcpmsChecklistConnection, error) {
	scope := coredata.NewScope(documentID.TenantID())

	items, err := r.probo.IcpmsChecklists.ListForDocument(ctx, scope, documentID, documentVersionID)
	if err != nil {
		return nil, fmt.Errorf("cannot list checklists by document: %w", err)
	}

	edges := make([]*types.IcpmsChecklistEdge, len(items))
	for i, item := range items {
		edges[i] = &types.IcpmsChecklistEdge{Node: item}
	}

	return &types.IcpmsChecklistConnection{
		Edges:      edges,
		TotalCount: len(items),
		PageInfo:   &types.PageInfo{},
	}, nil
}

// IcpmsChecklist returns schema.IcpmsChecklistResolver implementation.
func (r *Resolver) IcpmsChecklist() schema.IcpmsChecklistResolver { return &icpmsChecklistResolver{r} }

type icpmsChecklistResolver struct{ *Resolver }
