package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// Document is the resolver for the document field.
func (r *icpmsIngestionJobResolver) Document(ctx context.Context, obj *coredata.IcpmsIngestionJob) (*types.IcpmsDocument, error) {
	doc, err := r.probo.IcpmsDocuments.Get(ctx, coredata.NewScope(obj.TenantID), obj.DocumentID)
	if err != nil {
		return types.NewIcpmsDocument(&coredata.IcpmsDocument{
			ID:           obj.DocumentID,
			Code:         "DELETED",
			Title:        "[Tài liệu đã bị xóa]",
			DocumentType: "OTHER_EXTERNAL",
			Status:       "ARCHIVED",
		}), nil
	}
	return types.NewIcpmsDocument(doc), nil
}

// DocumentVersion is the resolver for the documentVersion field.
func (r *icpmsIngestionJobResolver) DocumentVersion(ctx context.Context, obj *coredata.IcpmsIngestionJob) (*types.IcpmsDocumentVersion, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScope(obj.TenantID), obj.DocumentVersionID)
	if err != nil {
		return types.NewIcpmsDocumentVersion(&coredata.IcpmsDocumentVersion{
			ID:          obj.DocumentVersionID,
			VersionCode: "DELETED",
			Status:      "EXPIRED",
		}), nil
	}
	return types.NewIcpmsDocumentVersion(version), nil
}

// DocumentFile is the resolver for the documentFile field.
func (r *icpmsIngestionJobResolver) DocumentFile(ctx context.Context, obj *coredata.IcpmsIngestionJob) (*types.IcpmsDocumentFile, error) {
	file, err := r.probo.IcpmsDocumentFiles.GetByID(ctx, coredata.NewScope(obj.TenantID), obj.DocumentFileID)
	if err != nil {
		return types.NewIcpmsDocumentFile(&coredata.IcpmsDocumentFile{
			ID:               obj.DocumentFileID,
			OriginalFileName: obj.FileNameSnapshot,
			UploadStatus:     "DELETED",
		}), nil
	}
	return types.NewIcpmsDocumentFile(file), nil
}

// CreateIcpmsIngestionJob is the resolver for the createIcpmsIngestionJob field.
func (r *mutationResolver) CreateIcpmsIngestionJob(ctx context.Context, input types.CreateIcpmsIngestionJobInput) (*types.CreateIcpmsIngestionJobPayload, error) {
	docID := input.DocumentID
	versionID := input.DocumentVersionID
	fileID := input.DocumentFileID

	scope, err := r.authorize(ctx, docID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	// Determine job type (default TEXT_EXTRACTION).
	jobType := coredata.IcpmsIngestionJobTypeTextExtraction
	if input.JobType != nil {
		jobType = coredata.IcpmsIngestionJobType(*input.JobType)
	}

	// Block duplicate QUEUED/RUNNING jobs for the same file.
	hasActive, err := r.probo.IcpmsIngestionJobs.HasActiveJobForFile(ctx, scope, fileID)
	if err != nil {
		return nil, fmt.Errorf("cannot check active jobs: %w", err)
	}
	if hasActive {
		return nil, fmt.Errorf("file này đang có job bóc tách đang chạy (QUEUED/RUNNING). Vui lòng đợi job hoàn thành trước khi tạo job mới.")
	}

	// For TEXT_EXTRACTION, block if a COMPLETED job already exists for the same file.
	if jobType == coredata.IcpmsIngestionJobTypeTextExtraction {
		existing, err := r.probo.IcpmsIngestionJobs.GetLatestForFile(ctx, scope, fileID)
		if err != nil {
			return nil, fmt.Errorf("cannot check existing jobs: %w", err)
		}
		if existing != nil && existing.Status == coredata.IcpmsIngestionJobStatusCompleted {
			return nil, fmt.Errorf("file này đã có job bóc tách hoàn thành. Chọn jobType RE_EXTRACTION để chạy lại bóc tách.")
		}
	}

	// Fetch the document file to populate snapshot fields and org ID on the job record.
	docFile, err := r.probo.IcpmsDocumentFiles.GetByID(ctx, scope, fileID)
	if err != nil {
		return nil, fmt.Errorf("cannot load document file: %w", err)
	}

	doc, docErr := r.probo.IcpmsDocuments.Get(ctx, scope, docID)
	fallbackIngCode := fmt.Sprintf("ING-%s-%d", docID.String()[16:], time.Now().Unix())
	ingCode := fallbackIngCode
	if docErr == nil {
		ingCode = r.probo.IcpmsCodes.BusinessCodeForDocument(ctx, scope, docFile.OrganizationID, "ING", doc, fallbackIngCode)
	}

	job := &coredata.IcpmsIngestionJob{
		TenantID:          docID.TenantID(),
		OrganizationID:    docFile.OrganizationID,
		DocumentID:        docID,
		DocumentVersionID: versionID,
		DocumentFileID:    fileID,
		JobCode:           ingCode,
		JobType:           jobType,
		ExtractionMode:    coredata.IcpmsIngestionExtractionMode(input.ExtractionMode),
		Status:            coredata.IcpmsIngestionJobStatusQueued,
		FileNameSnapshot:  docFile.OriginalFileName,
		FileTypeSnapshot:  docFile.FileType,
		FileSizeSnapshot:  docFile.FileSize,
		CreatedBy:         authn.IdentityFromContext(ctx).ID,
	}

	if err := r.probo.IcpmsIngestionJobs.Create(ctx, scope, job); err != nil {
		return nil, err
	}

	// Launch background worker with a detached context so the HTTP request
	// lifecycle does not cancel mid-extraction.
	go func(workerJob *coredata.IcpmsIngestionJob, workerScope coredata.Scoper) {
		bgCtx := context.Background()
		if err := r.probo.IcpmsIngestionJobs.ProcessJob(bgCtx, workerScope, workerJob); err != nil {
			r.logger.ErrorCtx(bgCtx, "ingestion job processing failed",
				log.String("job_id", workerJob.ID.String()),
				log.Error(err),
			)
		}
	}(job, scope)

	return &types.CreateIcpmsIngestionJobPayload{
		Job: job,
	}, nil
}

// DeleteIcpmsIngestionJob is the resolver for the deleteIcpmsIngestionJob field.
func (r *mutationResolver) DeleteIcpmsIngestionJob(ctx context.Context, input types.DeleteIcpmsIngestionJobInput) (*types.DeleteIcpmsIngestionJobPayload, error) {
	scope := coredata.NewScope(input.ID.TenantID())
	if err := r.probo.IcpmsIngestionJobs.Delete(ctx, scope, input.ID); err != nil {
		return nil, fmt.Errorf("failed to delete ingestion job: %w", err)
	}
	deletedID := input.ID
	return &types.DeleteIcpmsIngestionJobPayload{
		DeletedID: &deletedID,
	}, nil
}

// IngestionJobs is the resolver for the ingestionJobs field.
// Lists all ingestion jobs for the given organization, newest first.
func (r *queryResolver) IngestionJobs(ctx context.Context, organizationID gid.GID) (*types.IcpmsIngestionJobConnection, error) {
	scope := coredata.NewScopeFromObjectID(organizationID)

	jobs, err := r.probo.IcpmsIngestionJobs.ListForTenant(ctx, scope, 200)
	if err != nil {
		return nil, fmt.Errorf("cannot list ingestion jobs: %w", err)
	}

	edges := make([]*types.IcpmsIngestionJobEdge, len(jobs))
	for i, job := range jobs {
		edges[i] = &types.IcpmsIngestionJobEdge{Node: job}
	}

	return &types.IcpmsIngestionJobConnection{
		Edges:      edges,
		TotalCount: len(jobs),
		PageInfo:   &types.PageInfo{},
	}, nil
}

// IngestionJob is the resolver for the ingestionJob field.
func (r *queryResolver) IngestionJob(ctx context.Context, id gid.GID) (*coredata.IcpmsIngestionJob, error) {
	scope := coredata.NewScope(id.TenantID())
	job, err := r.probo.IcpmsIngestionJobs.Get(ctx, scope, id)
	if err != nil {
		return nil, fmt.Errorf("cannot get ingestion job: %w", err)
	}
	return job, nil
}

// IngestionJobTextBlocks returns the extracted text blocks for a completed ingestion job.
func (r *queryResolver) IngestionJobTextBlocks(ctx context.Context, jobID gid.GID) (*types.IcpmsExtractedTextBlockConnection, error) {
	scope := coredata.NewScope(jobID.TenantID())

	blocks, err := r.probo.IcpmsIngestionJobs.ListTextBlocksForJob(ctx, scope, jobID)
	if err != nil {
		return nil, fmt.Errorf("cannot list text blocks: %w", err)
	}

	edges := make([]*types.IcpmsExtractedTextBlockEdge, len(blocks))
	for i, b := range blocks {
		edges[i] = &types.IcpmsExtractedTextBlockEdge{Node: b}
	}

	return &types.IcpmsExtractedTextBlockConnection{
		Edges:      edges,
		TotalCount: len(edges),
		PageInfo:   &types.PageInfo{},
	}, nil
}

// LatestIngestionJobForFile is the resolver for the latestIngestionJobForFile field.
func (r *queryResolver) LatestIngestionJobForFile(ctx context.Context, documentFileID gid.GID) (*coredata.IcpmsIngestionJob, error) {
	scope := coredata.NewScope(documentFileID.TenantID())
	job, err := r.probo.IcpmsIngestionJobs.GetLatestForFile(ctx, scope, documentFileID)
	if err != nil {
		return nil, err
	}
	return job, nil
}

// LatestIngestionJobForVersion is the resolver for the latestIngestionJobForVersion field.
func (r *queryResolver) LatestIngestionJobForVersion(ctx context.Context, documentVersionID gid.GID) (*coredata.IcpmsIngestionJob, error) {
	scope := coredata.NewScope(documentVersionID.TenantID())
	job, err := r.probo.IcpmsIngestionJobs.GetLatestForVersion(ctx, scope, documentVersionID)
	if err != nil {
		return nil, err
	}
	return job, nil
}

// IcpmsIngestionJob returns schema.IcpmsIngestionJobResolver implementation.
func (r *Resolver) IcpmsIngestionJob() schema.IcpmsIngestionJobResolver {
	return &icpmsIngestionJobResolver{r}
}

type icpmsIngestionJobResolver struct{ *Resolver }
