package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// Files is the resolver for the files field.
func (r *icpmsDocumentVersionResolver) Files(ctx context.Context, obj *types.IcpmsDocumentVersion, first *int, after *page.CursorKey, last *int, before *page.CursorKey, filter *types.IcpmsDocumentFileFilter, orderBy *types.IcpmsDocumentFileOrderField) (*types.IcpmsDocumentFileConnection, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(obj.ID), obj.ID)
	if err != nil {
		return nil, err
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentGet)
	if err != nil {
		return nil, err
	}

	req := coredata.IcpmsDocumentFileFilter{
		DocumentVersionID: &obj.ID,
	}

	if filter != nil {
		if len(filter.UploadStatuses) > 0 {
			statuses := make([]coredata.IcpmsDocumentFileStatus, len(filter.UploadStatuses))
			for i, s := range filter.UploadStatuses {
				statuses[i] = coredata.IcpmsDocumentFileStatus(s)
			}
			req.UploadStatuses = statuses
		}
		req.IsActive = filter.IsActive
	}

	var ob coredata.IcpmsDocumentFileOrderField
	if orderBy != nil {
		ob = coredata.IcpmsDocumentFileOrderField(*orderBy)
	}

	limit := 50
	if first != nil {
		limit = *first
	}

	cursor := page.NewCursor(limit, after, page.Head, page.OrderBy[coredata.IcpmsDocumentFileOrderField]{
		Field:     ob,
		Direction: page.OrderDirectionDesc,
	})
	p, err := r.probo.IcpmsDocumentFiles.ListForDocumentVersion(ctx, scope, obj.ID, cursor, &req)
	if err != nil {
		return nil, err
	}

	return types.NewIcpmsDocumentFileConnection(p, obj, obj.ID, &req), nil
}

// LatestIngestionJob is the resolver for the latestIngestionJob field.
func (r *icpmsDocumentVersionResolver) LatestIngestionJob(ctx context.Context, obj *types.IcpmsDocumentVersion) (*coredata.IcpmsIngestionJob, error) {
	job, err := r.probo.IcpmsIngestionJobs.GetLatestForVersion(ctx, coredata.NewScopeFromObjectID(obj.ID), obj.ID)
	if err != nil {
		return nil, err
	}
	return job, nil
}

// CreateIcpmsDocumentVersion is the resolver for the createIcpmsDocumentVersion field.
func (r *mutationResolver) CreateIcpmsDocumentVersion(ctx context.Context, input types.CreateIcpmsDocumentVersionInput) (*types.CreateIcpmsDocumentVersionPayload, error) {
	scope, err := r.authorize(ctx, input.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	doc, err := r.probo.IcpmsDocuments.Get(ctx, scope, input.DocumentID)
	if err != nil {
		return nil, fmt.Errorf("cannot find document: %w", err)
	}

	version := &coredata.IcpmsDocumentVersion{
		OrganizationID:      doc.OrganizationID,
		DocumentID:          input.DocumentID,
		VersionCode:         input.VersionCode,
		VersionName:         input.VersionName,
		Edition:             input.Edition,
		Amendment:           input.Amendment,
		VersionNumber:       input.VersionNumber,
		PublicationDate:     input.PublicationDate,
		EffectiveDate:       input.EffectiveDate,
		ExpiryDate:          input.ExpiryDate,
		SupersedesVersionID: input.SupersedesVersionID,
		Status:              coredata.IcpmsDocumentVersionStatus(input.Status),
		IsCurrent:           input.IsCurrent,
		ChangeSummary:       input.ChangeSummary,
		Notes:               input.Notes,
		RawFileStatus:       coredata.IcpmsDocumentVersionRawFileStatusNotUploaded,
	}

	if err := r.probo.IcpmsDocumentVersions.Create(ctx, scope, version); err != nil {
		return nil, fmt.Errorf("cannot create icpms document version: %w", err)
	}

	if input.IsCurrent {
		if err := r.probo.IcpmsDocumentVersions.SetCurrentVersion(ctx, scope, version.ID); err != nil {
			return nil, fmt.Errorf("cannot set current version: %w", err)
		}
	}

	return &types.CreateIcpmsDocumentVersionPayload{
		Version: types.NewIcpmsDocumentVersion(version),
	}, nil
}

// UpdateIcpmsDocumentVersion is the resolver for the updateIcpmsDocumentVersion field.
func (r *mutationResolver) UpdateIcpmsDocumentVersion(ctx context.Context, input types.UpdateIcpmsDocumentVersionInput) (*types.UpdateIcpmsDocumentVersionPayload, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(input.ID), input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot load icpms document version: %w", err)
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	if input.VersionCode != nil {
		version.VersionCode = *input.VersionCode
	}
	if input.VersionName != nil {
		version.VersionName = *input.VersionName
	}
	if input.Edition != nil {
		version.Edition = input.Edition
	}
	if input.Amendment != nil {
		version.Amendment = input.Amendment
	}
	if input.VersionNumber != nil {
		version.VersionNumber = input.VersionNumber
	}
	if input.PublicationDate != nil {
		version.PublicationDate = input.PublicationDate
	}
	if input.EffectiveDate != nil {
		version.EffectiveDate = input.EffectiveDate
	}
	if input.ExpiryDate != nil {
		version.ExpiryDate = input.ExpiryDate
	}
	if input.SupersedesVersionID != nil {
		version.SupersedesVersionID = input.SupersedesVersionID
	}
	if input.Status != nil {
		version.Status = coredata.IcpmsDocumentVersionStatus(*input.Status)
	}
	if input.IsCurrent != nil {
		version.IsCurrent = *input.IsCurrent
	}
	if input.ChangeSummary != nil {
		version.ChangeSummary = input.ChangeSummary
	}
	if input.Notes != nil {
		version.Notes = input.Notes
	}

	if err := r.probo.IcpmsDocumentVersions.Update(ctx, scope, version); err != nil {
		return nil, fmt.Errorf("cannot update icpms document version: %w", err)
	}

	if input.IsCurrent != nil && *input.IsCurrent {
		if err := r.probo.IcpmsDocumentVersions.SetCurrentVersion(ctx, scope, version.ID); err != nil {
			return nil, fmt.Errorf("cannot set current version: %w", err)
		}
	}

	return &types.UpdateIcpmsDocumentVersionPayload{
		Version: types.NewIcpmsDocumentVersion(version),
	}, nil
}

// DeleteIcpmsDocumentVersion is the resolver for the deleteIcpmsDocumentVersion field.
func (r *mutationResolver) DeleteIcpmsDocumentVersion(ctx context.Context, input types.DeleteIcpmsDocumentVersionInput) (*types.DeleteIcpmsDocumentVersionPayload, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(input.ID), input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot load icpms document version: %w", err)
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	if err := r.probo.IcpmsDocumentVersions.Delete(ctx, scope, version); err != nil {
		return nil, fmt.Errorf("cannot delete icpms document version: %w", err)
	}

	return &types.DeleteIcpmsDocumentVersionPayload{
		ID: input.ID,
	}, nil
}

// SetIcpmsDocumentVersionCurrent is the resolver for the setIcpmsDocumentVersionCurrent field.
func (r *mutationResolver) SetIcpmsDocumentVersionCurrent(ctx context.Context, input types.SetIcpmsDocumentVersionCurrentInput) (*types.SetIcpmsDocumentVersionCurrentPayload, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(input.ID), input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot load icpms document version: %w", err)
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	if err := r.probo.IcpmsDocumentVersions.SetCurrentVersion(ctx, scope, input.ID); err != nil {
		return nil, fmt.Errorf("cannot set current version: %w", err)
	}

	version, err = r.probo.IcpmsDocumentVersions.Get(ctx, scope, input.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot reload icpms document version: %w", err)
	}

	return &types.SetIcpmsDocumentVersionCurrentPayload{
		Version: types.NewIcpmsDocumentVersion(version),
	}, nil
}

// IcpmsDocumentVersion returns schema.IcpmsDocumentVersionResolver implementation.
func (r *Resolver) IcpmsDocumentVersion() schema.IcpmsDocumentVersionResolver {
	return &icpmsDocumentVersionResolver{r}
}

type icpmsDocumentVersionResolver struct{ *Resolver }
