package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// CreateAndRunVietnameseParseJob is the resolver for the createAndRunVietnameseParseJob field.
func (r *mutationResolver) CreateAndRunVietnameseParseJob(ctx context.Context, input types.CreateIcpmsDocumentParseJobInput) (*types.CreateIcpmsDocumentParseJobPayload, error) {
	ingestionJobID := input.IngestionJobID
	scope := coredata.NewScope(ingestionJobID.TenantID())
	identity := authn.IdentityFromContext(ctx)

	parseJob, err := r.probo.IcpmsParseJobs.CreateAndRunVietnamese(ctx, scope, ingestionJobID, identity.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot run Vietnamese parser: %w", err)
	}

	return &types.CreateIcpmsDocumentParseJobPayload{
		ParseJob: parseJob,
	}, nil
}

// CreateAndRunIcaoParseJob is the resolver for the createAndRunIcaoParseJob field.
func (r *mutationResolver) CreateAndRunIcaoParseJob(ctx context.Context, input types.CreateIcpmsDocumentParseJobInput) (*types.CreateIcpmsDocumentParseJobPayload, error) {
	ingestionJobID := input.IngestionJobID
	scope := coredata.NewScope(ingestionJobID.TenantID())
	identity := authn.IdentityFromContext(ctx)

	parseJob, err := r.probo.IcpmsParseJobs.CreateAndRunIcaoEnglish(ctx, scope, ingestionJobID, identity.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot run ICAO parser: %w", err)
	}

	return &types.CreateIcpmsDocumentParseJobPayload{
		ParseJob: parseJob,
	}, nil
}

// LatestParseJobForIngestionJob is the resolver for the latestParseJobForIngestionJob field.
func (r *queryResolver) LatestParseJobForIngestionJob(ctx context.Context, ingestionJobID gid.GID) (*coredata.IcpmsDocumentParseJob, error) {
	scope := coredata.NewScope(ingestionJobID.TenantID())
	job, err := r.probo.IcpmsParseJobs.GetLatestForIngestionJob(ctx, scope, ingestionJobID)
	if err != nil {
		return nil, fmt.Errorf("cannot get parse job: %w", err)
	}
	return job, nil
}

// LatestIcaoParseJobForIngestionJob is the resolver for the latestIcaoParseJobForIngestionJob field.
func (r *queryResolver) LatestIcaoParseJobForIngestionJob(ctx context.Context, ingestionJobID gid.GID) (*coredata.IcpmsDocumentParseJob, error) {
	scope := coredata.NewScope(ingestionJobID.TenantID())
	job, err := r.probo.IcpmsParseJobs.GetLatestIcaoForIngestionJob(ctx, scope, ingestionJobID)
	if err != nil {
		return nil, fmt.Errorf("cannot get ICAO parse job: %w", err)
	}
	return job, nil
}

// ParsedSectionsForJob is the resolver for the parsedSectionsForJob field.
func (r *queryResolver) ParsedSectionsForJob(ctx context.Context, parseJobID gid.GID) ([]*coredata.IcpmsParsedDocumentSection, error) {
	scope := coredata.NewScope(parseJobID.TenantID())
	sections, err := r.probo.IcpmsParseJobs.ListSectionsForJob(ctx, scope, parseJobID)
	if err != nil {
		return nil, fmt.Errorf("cannot list parsed sections: %w", err)
	}
	return sections, nil
}
