package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// UploadIcpmsDocumentFile is the resolver for the uploadIcpmsDocumentFile field.
func (r *mutationResolver) UploadIcpmsDocumentFile(ctx context.Context, input types.UploadIcpmsDocumentFileInput) (*types.UploadIcpmsDocumentFilePayload, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(input.DocumentVersionID), input.DocumentVersionID)
	if err != nil {
		return nil, err
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	req := probo.UploadIcpmsDocumentFileRequest{
		DocumentVersionID: input.DocumentVersionID,
		File: probo.FileUpload{
			Filename:    input.File.Filename,
			Size:        input.File.Size,
			Content:     input.File.File,
			ContentType: input.File.ContentType,
		},
		UploadedBy: authn.IdentityFromContext(ctx).ID,
	}

	icpmsFile, err := r.probo.IcpmsDocumentFiles.Upload(ctx, scope, req, false)
	if err != nil {
		return nil, err
	}

	return &types.UploadIcpmsDocumentFilePayload{
		File:            types.NewIcpmsDocumentFile(icpmsFile),
		DocumentVersion: types.NewIcpmsDocumentVersion(version),
	}, nil
}

// ReplaceIcpmsDocumentFile is the resolver for the replaceIcpmsDocumentFile field.
func (r *mutationResolver) ReplaceIcpmsDocumentFile(ctx context.Context, input types.ReplaceIcpmsDocumentFileInput) (*types.ReplaceIcpmsDocumentFilePayload, error) {
	version, err := r.probo.IcpmsDocumentVersions.Get(ctx, coredata.NewScopeFromObjectID(input.DocumentVersionID), input.DocumentVersionID)
	if err != nil {
		return nil, err
	}

	scope, err := r.authorize(ctx, version.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	req := probo.UploadIcpmsDocumentFileRequest{
		DocumentVersionID: input.DocumentVersionID,
		File: probo.FileUpload{
			Filename:    input.File.Filename,
			Size:        input.File.Size,
			Content:     input.File.File,
			ContentType: input.File.ContentType,
		},
		UploadedBy: authn.IdentityFromContext(ctx).ID,
	}

	icpmsFile, err := r.probo.IcpmsDocumentFiles.Upload(ctx, scope, req, true)
	if err != nil {
		return nil, err
	}

	return &types.ReplaceIcpmsDocumentFilePayload{
		File:            types.NewIcpmsDocumentFile(icpmsFile),
		DocumentVersion: types.NewIcpmsDocumentVersion(version),
	}, nil
}

// DeleteIcpmsDocumentFile is the resolver for the deleteIcpmsDocumentFile field.
func (r *mutationResolver) DeleteIcpmsDocumentFile(ctx context.Context, input types.DeleteIcpmsDocumentFileInput) (*types.DeleteIcpmsDocumentFilePayload, error) {
	file, err := r.probo.IcpmsDocumentFiles.GetByID(ctx, coredata.NewScopeFromObjectID(input.ID), input.ID)
	if err != nil {
		return nil, err
	}

	scope, err := r.authorize(ctx, file.DocumentID, probo.ActionDocumentUpdate)
	if err != nil {
		return nil, err
	}

	err = r.probo.IcpmsDocumentFiles.SoftDelete(ctx, scope, input.ID)
	if err != nil {
		return nil, err
	}

	return &types.DeleteIcpmsDocumentFilePayload{
		ID: input.ID,
	}, nil
}

// GenerateIcpmsDocumentFileDownloadURL is the resolver for the generateIcpmsDocumentFileDownloadUrl field.
func (r *mutationResolver) GenerateIcpmsDocumentFileDownloadURL(ctx context.Context, input types.GenerateIcpmsDocumentFileDownloadURLInput) (*types.GenerateIcpmsDocumentFileDownloadURLPayload, error) {
	file, err := r.probo.IcpmsDocumentFiles.GetByID(ctx, coredata.NewScopeFromObjectID(input.ID), input.ID)
	if err != nil {
		return nil, err
	}

	scope, err := r.authorize(ctx, file.DocumentID, probo.ActionDocumentGet)
	if err != nil {
		return nil, err
	}

	// Token expires in 1 hour
	url, err := r.probo.IcpmsDocumentFiles.GenerateDownloadURL(ctx, scope, input.ID, 3600*time.Second)
	if err != nil {
		return nil, err
	}

	return &types.GenerateIcpmsDocumentFileDownloadURLPayload{
		DownloadURL: url,
	}, nil
}
