package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
)

// Document is the resolver for the document field.
func (r *icpmsRequirementResolver) Document(ctx context.Context, obj *coredata.IcpmsRequirement) (*types.IcpmsDocument, error) {
	scope := coredata.NewScope(obj.TenantID)
	doc, err := r.probo.IcpmsDocuments.Get(ctx, scope, obj.DocumentID)
	if err != nil {
		return types.NewIcpmsDocument(&coredata.IcpmsDocument{
			ID:           obj.DocumentID,
			Code:         "N/A",
			Title:        "[Tài liệu không tìm thấy]",
			DocumentType: "OTHER_EXTERNAL",
			Status:       "ARCHIVED",
		}), nil
	}
	return types.NewIcpmsDocument(doc), nil
}

// RequirementType is the resolver for the requirementType field.
func (r *icpmsRequirementResolver) RequirementType(ctx context.Context, obj *coredata.IcpmsRequirement) (types.IcpmsRequirementType, error) {
	return types.IcpmsRequirementType(obj.RequirementType), nil
}

// ApplicabilityStatus is the resolver for the applicabilityStatus field.
func (r *icpmsRequirementResolver) ApplicabilityStatus(ctx context.Context, obj *coredata.IcpmsRequirement) (types.IcpmsApplicabilityStatus, error) {
	return types.IcpmsApplicabilityStatus(obj.ApplicabilityStatus), nil
}

// ReviewStatus is the resolver for the reviewStatus field.
func (r *icpmsRequirementResolver) ReviewStatus(ctx context.Context, obj *coredata.IcpmsRequirement) (types.IcpmsRequirementReviewStatus, error) {
	return types.IcpmsRequirementReviewStatus(obj.ReviewStatus), nil
}

// Priority is the resolver for the priority field.
func (r *icpmsRequirementResolver) Priority(ctx context.Context, obj *coredata.IcpmsRequirement) (types.IcpmsRequirementPriority, error) {
	return types.IcpmsRequirementPriority(obj.Priority), nil
}

// Status is the resolver for the status field.
func (r *icpmsRequirementGenerationJobResolver) Status(ctx context.Context, obj *coredata.IcpmsRequirementGenerationJob) (types.IcpmsRequirementGenerationJobStatus, error) {
	return types.IcpmsRequirementGenerationJobStatus(obj.Status), nil
}

// GenerateRequirementsFromParseJob is the resolver for the generateRequirementsFromParseJob field.
func (r *mutationResolver) GenerateRequirementsFromParseJob(ctx context.Context, input types.GenerateRequirementsFromParseJobInput) (*types.GenerateRequirementsPayload, error) {
	parseJobID := input.ParseJobID
	scope := coredata.NewScope(parseJobID.TenantID())
	identity := authn.IdentityFromContext(ctx)

	genJob, created, err := r.probo.IcpmsRequirements.GenerateFromParseJob(ctx, scope, parseJobID, identity.ID)
	if err != nil {
		return nil, fmt.Errorf("cannot generate requirements: %w", err)
	}

	return &types.GenerateRequirementsPayload{
		GenerationJob:       genJob,
		RequirementsCreated: created,
	}, nil
}

// UpdateIcpmsRequirement is the resolver for the updateIcpmsRequirement field.
func (r *mutationResolver) UpdateIcpmsRequirement(ctx context.Context, input types.UpdateIcpmsRequirementInput) (*types.UpdateIcpmsRequirementPayload, error) {
	reqID := input.ID
	scope := coredata.NewScope(reqID.TenantID())

	var reqType *coredata.IcpmsRequirementType
	if input.RequirementType != nil {
		v := coredata.IcpmsRequirementType(*input.RequirementType)
		reqType = &v
	}
	var appStatus *coredata.IcpmsApplicabilityStatus
	if input.ApplicabilityStatus != nil {
		v := coredata.IcpmsApplicabilityStatus(*input.ApplicabilityStatus)
		appStatus = &v
	}
	var reviewStatus *coredata.IcpmsRequirementReviewStatus
	if input.ReviewStatus != nil {
		v := coredata.IcpmsRequirementReviewStatus(*input.ReviewStatus)
		reviewStatus = &v
	}
	var priority *coredata.IcpmsRequirementPriority
	if input.Priority != nil {
		v := coredata.IcpmsRequirementPriority(*input.Priority)
		priority = &v
	}

	req, err := r.probo.IcpmsRequirements.Update(ctx, scope, reqID,
		input.Title, input.Description,
		reqType, appStatus, reviewStatus, priority,
	)
	if err != nil {
		return nil, fmt.Errorf("cannot update requirement: %w", err)
	}

	return &types.UpdateIcpmsRequirementPayload{Requirement: req}, nil
}

// IcpmsRequirementsForOrganization is the resolver for the icpmsRequirementsForOrganization field.
func (r *queryResolver) IcpmsRequirementsForOrganization(ctx context.Context, organizationID gid.GID, filter *types.IcpmsRequirementsFilterInput) ([]*coredata.IcpmsRequirement, error) {
	scope := coredata.NewScope(organizationID.TenantID())

	var svcFilter *probo.IcpmsRequirementsFilter
	if filter != nil {
		svcFilter = &probo.IcpmsRequirementsFilter{}
		if filter.ParseJobID != nil {
			svcFilter.ParseJobID = filter.ParseJobID
		}
		if filter.RequirementType != nil {
			v := coredata.IcpmsRequirementType(*filter.RequirementType)
			svcFilter.RequirementType = &v
		}
		if filter.ReviewStatus != nil {
			v := coredata.IcpmsRequirementReviewStatus(*filter.ReviewStatus)
			svcFilter.ReviewStatus = &v
		}
		if filter.ApplicabilityStatus != nil {
			v := coredata.IcpmsApplicabilityStatus(*filter.ApplicabilityStatus)
			svcFilter.ApplicabilityStatus = &v
		}
		if filter.Priority != nil {
			v := coredata.IcpmsRequirementPriority(*filter.Priority)
			svcFilter.Priority = &v
		}
	}

	reqs, err := r.probo.IcpmsRequirements.List(ctx, scope, organizationID, svcFilter)
	if err != nil {
		return nil, fmt.Errorf("cannot list requirements: %w", err)
	}
	return reqs, nil
}

// LatestRequirementGenerationJobForParseJob is the resolver for the latestRequirementGenerationJobForParseJob field.
func (r *queryResolver) LatestRequirementGenerationJobForParseJob(ctx context.Context, parseJobID gid.GID) (*coredata.IcpmsRequirementGenerationJob, error) {
	scope := coredata.NewScope(parseJobID.TenantID())
	job, err := r.probo.IcpmsRequirements.GetLatestGenerationJobForParseJob(ctx, scope, parseJobID)
	if err != nil {
		return nil, fmt.Errorf("cannot get generation job: %w", err)
	}
	return job, nil
}

// IcpmsRequirement returns schema.IcpmsRequirementResolver implementation.
func (r *Resolver) IcpmsRequirement() schema.IcpmsRequirementResolver {
	return &icpmsRequirementResolver{r}
}

// IcpmsRequirementGenerationJob returns schema.IcpmsRequirementGenerationJobResolver implementation.
func (r *Resolver) IcpmsRequirementGenerationJob() schema.IcpmsRequirementGenerationJobResolver {
	return &icpmsRequirementGenerationJobResolver{r}
}

type icpmsRequirementResolver struct{ *Resolver }
type icpmsRequirementGenerationJobResolver struct{ *Resolver }
