name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "runs-on/action@742bf56072eb4845a0f94b3394673e4903c90ff0" # v2
      - uses: "trufflesecurity/trufflehog@5f47aad1c2df34f7c6230784ce9a5a659922f479" # main
        with:
          extra_args: "--results=verified,unknown --exclude-paths=.trufflehog-exclude"
